OPI xPU Aware CSIs
opiproject/opi-api pull request #113
Opened 2022-09-08 17:12 UTC by mkalderon

Inception. Beginning of document and images trying to define how CSIs will interact with OPI-compatible xPUs in the data center.

Signed-off-by: Michal Kalderon <mkalderon@marvell.com>

2022-09-08 18:46 UTC, glimchb approved these changes
option1 makes the most sense to me, assuming DPUs are attached to Hosts... so there is a relationship there... vs Controller, which is one per Storage target system...

2022-09-08 19:45 UTC, seroyer commented on storage/opi-csi.md
> +![CSI without DPUs](../doc/images/CSI-With-xPU-option1.png)
This (and the ones below) need different alt text.

2022-09-08 19:45 UTC, seroyer commented on storage/opi-csi.md
> +The second option is that the CSI Driver Controller will be the one configuring the DPU and the node driver will only be informed of its local nvme device
Need to replace the remaining "DPU" terms with "xPU"

2022-09-08 21:40 UTC, glimchb commented
@intelfisz fyi

2022-09-09 10:26 UTC, intelfisz commented
@glimchb I also assume option 1 to be the right one - the standard flow is associated with controller communicating connection information to node drivers - I see no reason to change that, especially since changes are confined to node driver only in this case.

2022-09-09 13:20 UTC, mestery requested changes
The diagrams all have titles with DPUs, can you change this to xPU please?

2022-09-09 13:20 UTC, mestery commented on storage/opi-csi.md
> +![CSI without DPUs](../doc/images/CSI-With-xPU-option1.png)
Agree with Steve.

2022-09-09 13:22 UTC, mkalderon commented on storage/opi-csi.md
> +![CSI without DPUs](../doc/images/CSI-With-xPU-option1.png)
right, will fix

2022-09-09 13:23 UTC, mkalderon commented on storage/opi-csi.md
> +The second option is that the CSI Driver Controller will be the one configuring the DPU and the node driver will only be informed of its local nvme device
Missed this one! will fix

2022-09-09 13:35 UTC, glimchb commented
> > option1 makes the most sense to me, assuming DPUs are attached to Hosts... so there is a relationship there... vs Controller, which is one per Storage target system...
> 
> option 3 could reduce the need for making changes per node-driver, will add more layering. But for newer drivers we could provide standard APIs that for their case would avoid the need for OPI node driver and interact directly with OPI controller driver.

we can open this to discussion in the next week API call, I will ask @sanders-mark to add this to the agenda

2022-09-09 14:03 UTC, mestery approved these changes
Thanks for the fixes on the naming!

2022-09-09 14:03 UTC, merged

2022-09-13 14:30 UTC, pohly reviewed
Hello! This looks like and interesting activity and something that is related to my work. I worked on a similar solution a while back (see below) and am one of the upstream developers working on CSI in Kubernetes. I am a SIG Storage reviewer and the maintainer of [csi-test](https://github.com/kubernetes-csi/csi-test).

I missed all other discussions around this, so let me simply dive in and leave some comments on what is in this PR...

2022-09-13 14:30 UTC, pohly commented on storage/opi-csi.md
> +![CSI With xPU option1](../doc/images/CSI-With-xPU-option1.png)
A general comment about the diagrams: it would be useful to describe what is being done in terms of CSI operations (`ControllerPublishVolume`, `NodeStageVolume`, `NodePublishVolume`) because then it is clearer what is meant. As it stands now, for example "during bind/mount to pod" is ambiguous: one typically happens during `NodeStageVolume` (mounting), the other during `NodePublishVolume` (bind to directory for a pod).

2022-09-13 14:30 UTC, pohly commented on storage/opi-csi.md
> +![CSI With xPU option1](../doc/images/CSI-With-xPU-option1.png)
The first option makes sense to me, assuming that there is a communication path between node driver and OPI gRPC. In particular the OPI API call can report back which VF has the intended volume.

2022-09-13 14:30 UTC, pohly commented on storage/opi-csi.md
> +![CSI with xPU option2](../doc/images/CSI-With-xPU-option2.png)
So in this case, `ControllerPublishVolume` will ensure that the volume is attached. The `publish_context` must contain information about the VF and will be made available to `NodeStageVolume`. That should work.

2022-09-13 14:30 UTC, pohly commented on storage/opi-csi.md
> +![CSI with xPU option3](../doc/images/CSI-With-xPU-option3.png)
This looks similar to the idea from https://github.com/intel/oim#storage--csi. The prototype had support for ceph-csi.

The overall question is: who delivers which components and provides support for them?

The third option makes it possible for an xPU vendor to add xPU support to an existing storage solution without the storage vendor doing anything. But then the xPU vendor is responsible for end-customer support.

The other two options invert the responsibility: the storage vendor must do something in their driver for xPUs and thus has the responsibility to validate and support the result.

2022-09-13 15:06 UTC, glimchb commented on storage/opi-csi.md
> +The xPU needs to receive remote storage information to enable it to connect to the remote target. There are several ways in which this information can be passed to the xPU. In all cases, there will b
good point, we haven't dived into secure considerations of the connection between client and server yet

2022-09-13 15:08 UTC, glimchb commented on storage/opi-csi.md
> +![CSI With xPU option1](../doc/images/CSI-With-xPU-option1.png)
exactly my though, OPI API call can report back which VF has the intended volume and then CSI node driver can use this information to find correct local NVMe device to bind/mount into the POD

regarding CSI exact operations comment - agree we need more details on this, all diagrams created using https://app.diagrams.net/ so if you have time, you can suggest an edit and help us out here

2022-09-13 15:10 UTC, glimchb commented on storage/opi-csi.md
> +![CSI with xPU option2](../doc/images/CSI-With-xPU-option2.png)
technically possible, yes, but I'm worried about scale a bit... in my mind if DPUs and IPUs are plugged into Server, then Node driver should be responsible to configure them... while Controller driver should have minimal changes and still only talk to Storage system... but SME opinion is what we need here, so chime in...

2022-09-13 15:35 UTC, pohly commented on storage/opi-csi.md
> +![CSI with xPU option3](../doc/images/CSI-With-xPU-option3.png)
This option could use the CSI controller from the storage vendor and the completely replace the node part. That should work as long as the controller really only handles volume provisioning and never communicates with the node part. At least for ceph-csi that was the case.

2022-09-13 15:38 UTC, pohly commented
> @pohly your timing is perfect, we just kicked of this discussion 4 days ago by this pull request and hope to have our `first` meeting this week API meeting https://lists.opiproject.org/g/opi/calendar you are welcome to join

Thursdays around that time are already fairly busy for me.

> also join on slack discussion https://opi-project.slack.com/archives/C03Q50JUWAU

I joined that Slack and will try to follow along.

2022-09-13 17:19 UTC, mkalderon commented on storage/opi-csi.md
> +![CSI with xPU option2](../doc/images/CSI-With-xPU-option2.png)
Need to also consider the case where DPU could be on the target side, in which case OPI could provide the means for API between controller + target.

2022-09-13 17:22 UTC, mkalderon commented on storage/opi-csi.md
> +![CSI with xPU option3](../doc/images/CSI-With-xPU-option3.png)
wouldn't xPU vendors need to add support for different storage solution anyway? even if they get information from node driver, they would need to know what to do with it -> or would storage providers provide a xPU driver ?

2022-09-13 18:00 UTC, glimchb commented on storage/opi-csi.md
> +![CSI with xPU option2](../doc/images/CSI-With-xPU-option2.png)
yes, thank you @mkalderon that is a new interesting use case

2022-09-13 18:04 UTC, glimchb commented on storage/opi-csi.md
> +![CSI with xPU option3](../doc/images/CSI-With-xPU-option3.png)
not always, let's say ALL storage products do NVMeoF for block storage (I know this is not the case) then xPU vendor will only need to provide NVMeoF initiator regardless of the target storage system. CSI will come from the storage vendor to provision this target storage system.

in cases where protocol is proprietary either xPU vendor or Storage vendor wil provide xPU driver - this is out of OPI scope anyways

2022-09-14 06:36 UTC, mkalderon commented on storage/opi-csi.md
> +![CSI with xPU option3](../doc/images/CSI-With-xPU-option3.png)
In the case you provided above, all node drivers just need to provide NVMeoF initiator - so how do they differ ? and if they don't differ, then they can be replace entirely by OPI node driver right ?

2022-09-14 11:12 UTC, glimchb commented on storage/opi-csi.md
> +![CSI with xPU option3](../doc/images/CSI-With-xPU-option3.png)
vendors usually provide the bundle Node-Controller as a single binary that can accept argument what personality to run... 
I don't think anybody doing separate deploy of unrelated node and ctrl drivers from different container images... 
let's ask our SME @pohly

2022-09-14 12:26 UTC, pohly commented on storage/opi-csi.md
> +![CSI with xPU option3](../doc/images/CSI-With-xPU-option3.png)
Providing a single binary and thus container image is convenient, but not required. I don't know whether everybody does it.

For the discussion above it doesn't matter: the relevant part is that the vendor has some install instructions for the node part of their driver. Instead of following those, a generic OPI node driver would need to be deployed instead.