netwrok protos for cloud apis
opiproject/opi-api pull request #128
Opened 2022-09-22 03:41 UTC by jainvipin

appreciate review of the network protos for cloud apis

2022-09-22 12:55 UTC, glimchb commented
@jainvipin few linter fixes in readme are needed per checker above

2022-09-22 17:07 UTC, glimchb commented
> This also needs a Makefile to allow for generation of golang APIs, similar to the above, and we should probably check in those golang generated files (and autogen.md) as well to keep things consistent.

before the API call today I was thinking we should just merge them directly under network folder and not create a new sub-folder... that would eliminate the need for additional scripting and CI...

2022-09-23 03:48 UTC, jainvipin commented
> @jainvipin few linter fixes in readme are needed per checker above

fixed @glimchb

2022-09-23 03:52 UTC, jainvipin commented
@mestery @glimchb - I can copy the Makefile from the base directory, and run make comments (i.e. run protoc generation and and also generate pb.go files from it, and fix any issues that I run into as a result, of course. Please let me know if that would be a better choice.

2022-09-23 14:06 UTC, glimchb commented
> @mestery @glimchb - I can copy the Makefile from the base directory, and run make comments (i.e. run protoc generation and and also generate pb.go files from it, and fix any issues that I run into as a result, of course. Please let me know if that would be a better choice.

since this is a big change, we can leave makefile and ci updates to a separate pull request once we merge this one

2022-09-23 16:28 UTC, sandersms commented
From what I have reviewed thus far, the addition looks good.  There is likely some alignment around some of the other models that we will need to look at.  For example the Openconfig_interfaces model and the interfaces protobuf here do have differences that we will need to rectify and perhaps pull into a common proto api that would handle cloud, enterprise, telco, etc. spaces.

We can add the CI/CD pipelines in a later pull request.

2022-09-23 17:51 UTC, sandersms commented on network/cloud-services/protos/interface.proto
> +// LLDP chassis/port Identifier key type
Is there a reason why LLDP is inside of the interface proto vs being a separate proto?  In the OpenConfig model LLDP is a separate entity that references the interfaces that have the capability enabled vs being internal to the interface model.

Just thinking on how to align various models with common and market specific.

2022-09-26 12:02 UTC, pathreya requested changes
I took a look at this submission from an overall "cloud services to DPU" perspective as well as focused more in the areas of route, interface, ipsec, nexthop, policy, tunnel, vnic, vpc configurations. I have a few comments and questions, some borne out of my curiosity/incognizance.

2022-09-26 20:06 UTC, jainvipin commented on network/cloud-services/protos/interface.proto
> +// LLDP chassis/port Identifier key type
usually LLDP would run on a physical/logical interface, hence kept it in the interface proto e.g. `LldpStatus` is used in uplink's status itself to know the status. Without this we'll need a named reference to LLDP object to navigate it there.

2022-09-26 20:14 UTC, jainvipin commented on network/cloud-services/README.md
> +- Network Servcies: network firewall, NAT, IPSec, mirroring, service load balancing, etc.
fixed servcies; thanks!
network protocols always have a peer to interoperate with, where as network services are typically are defined by a local implementation behavior upon controller's API calls, without having to interact with peer device using control plane messages.

Having said that: this is only for the documentation, as such the proto files look similar and appear without any implicit hierarchy.

2022-09-26 20:14 UTC, jainvipin commented on network/cloud-services/README.md
> +- Netwrok Protocols: most common protocols in cloud deployment such as bgp, evpn, and dhcp
fixed in the updated PR; thanks!

2022-09-26 20:26 UTC, jainvipin commented on network/cloud-services/protos/interface.proto
> +  IF_TYPE_NONE      = 0;
`NONE` allows forcing the user to choose an explicit value; usually the default structs are emptied out and user shouldn't accidentally select the interface type without having to specify it. We can discuss if this is a practice we want to adopt or go with the assumptions on default values for various fields/enums.

2022-09-26 20:27 UTC, jainvipin commented on network/cloud-services/protos/ipsec.proto
> +  ENCRYPTION_ALGORITHM_DES3        = 9;
happy to remove it, kept it there for completeness, as long as there are not implementations stil using it.

2022-09-26 22:19 UTC, jainvipin commented on network/cloud-services/protos/cp_route.proto
> +}
you are correct, we could reuse CPRouteKey here and streamline a few fields for completeness. let me come back on this one on what would be the right way to reusing CPRouteKey here.

2022-09-26 22:27 UTC, jainvipin commented on network/cloud-services/protos/mirror.proto
> +message MirrorRuleSpec {
I didn't get your comment fully here; `MirrorPolicy` has multiple `MirrorRules`, with each rule identifying the set of traffic to match and mirror the traffic to a destination specified in `MirrorSession` object

2022-09-26 22:59 UTC, jainvipin commented on network/cloud-services/protos/ipsec.proto
> +  uint64                  Iv                      = 10;
Yes initialization vector is practically the sequence number itself so may not make much sense in asking user about this info. I kept it for completeness.

About ESN - Agreed that ESN is needed, but whether to use ESN (extended) vs. 32-bit sequence number, is something IKE would negotiate - and so I am not sure if ESN is something we need in the configuration here. It will be used however in the ESP headers.

2022-09-26 23:04 UTC, jainvipin commented on network/cloud-services/protos/ipsec.proto
> +  IpsecProtocol           Protocol                = 2;
Agree AH alone is not too attractive, even though someone, in theory, can argue using it for data integrity and so I kept it for completeness. I am ok keeping it there or if everyone agrees, taking it out all together. More importantly, AH+ESP is a combination we can introduce if some vendor wants to support that. I agree ESP is the most prevalent and the likely protocol to be used for IPSec deployments. Let's discuss.

2022-09-26 23:38 UTC, AnuradhaKaruppiah commented
Thanks for sending the PR @jainvipin. The files in this commit upstream one vendor's NB. While they create a great starting point, merging this PR as-is without other vendors collaborating (committing to implement it or even reviewing it) in some fashion creates an unfair advantage to one vendor as it may now be perceived as "the" OPI NB.

To avoid that confusion and to use the content for what it is intended, as a discussion starting point, I will suggest moving the contents to a "Pensando" subdirectory. Once a collaborative NB is created based on the contributions from other OPI vendors and service providers it can be dropped into the main "cloud APIs". Do you think that would work?

2022-09-26 23:54 UTC, glimchb commented
@AnuradhaKaruppiah Nvidia more then welcome to upstream their NB APIs for OPI adoption review as well...

2022-09-26 23:59 UTC, AnuradhaKaruppiah commented
> @AnuradhaKaruppiah Nvidia more then welcome to upstream their NB APIs for OPI adoption review as well...

Yes Boris, that is certainly the plan.

2022-09-27 00:08 UTC, sandersms commented
> Thanks for sending the PR @jainvipin. The files in this commit upstream one vendor's NB. While they create a great starting point, merging this PR as-is without other vendors collaborating (committing to implement it or even reviewing it) in some fashion creates an unfair advantage to one vendor as it may now be perceived as "the" OPI NB.
> 
> To avoid that confusion and to use the content for what it is intended, as a discussion starting point, I will suggest moving the contents to a "Pensando" subdirectory. Once a collaborative NB is created based on the contributions from other OPI vendors and service providers it can be dropped into the main "cloud APIs". Do you think that would work?

@AnuradhaKaruppiah We don't want to go down the path of vendor directories.  That completely moves away from coming up with a common API.

2022-09-27 00:10 UTC, sandersms commented
We will leave this PR open for continued review and comments/discussion through 12 Oct 2022.  We will also discuss this at the meeting on 13 Oct 2022.  Please provide your comments on the contribution to continue the discussion.

2022-09-27 00:23 UTC, AnuradhaKaruppiah commented
> > Thanks for sending the PR @jainvipin. The files in this commit upstream one vendor's NB. While they create a great starting point, merging this PR as-is without other vendors collaborating (committing to implement it or even reviewing it) in some fashion creates an unfair advantage to one vendor as it may now be perceived as "the" OPI NB.
> > To avoid that confusion and to use the content for what it is intended, as a discussion starting point, I will suggest moving the contents to a "Pensando" subdirectory. Once a collaborative NB is created based on the contributions from other OPI vendors and service providers it can be dropped into the main "cloud APIs". Do you think that would work?
> 
> @AnuradhaKaruppiah We don't want to go down the path of vendor directories. That completely moves away from coming up with a common API.

@sandersms  So far OPI has been using the approach of merge as soon as one reviewer acks (and it seemed like that was fulfilled on this PR) hence my comments. If the PR is going to be held open till folks have had a chance to review that may work. I am unable to add other reviewers to the PR, do I need some special perms for that.

2022-09-27 00:29 UTC, sandersms commented
> > > Thanks for sending the PR @jainvipin. The files in this commit upstream one vendor's NB. While they create a great starting point, merging this PR as-is without other vendors collaborating (committing to implement it or even reviewing it) in some fashion creates an unfair advantage to one vendor as it may now be perceived as "the" OPI NB.
> > > To avoid that confusion and to use the content for what it is intended, as a discussion starting point, I will suggest moving the contents to a "Pensando" subdirectory. Once a collaborative NB is created based on the contributions from other OPI vendors and service providers it can be dropped into the main "cloud APIs". Do you think that would work?
> > 
> > 
> > @AnuradhaKaruppiah We don't want to go down the path of vendor directories. That completely moves away from coming up with a common API.
> 
> @sandersms So far OPI has been using the approach of merge as soon as one reviewer acks (and it seemed like that was fulfilled on this PR) hence my comments. If the PR is going to be held open till folks have had a chance to review that may work. I am unable to add other reviewers to the PR, do I need some special perms for that.

@AnuradhaKaruppiah This is is significant contribution and we are holding this PR open for comment and discussion until 12 October 2022 and we will discuss on 13 Oct 2022 in the meeting.  We have not approved nor merged this PR and comments and discussion continue.  That is the rational for my additional statement for holding this PR open for continued discussion.

2022-09-27 00:32 UTC, glimchb commented
@AnuradhaKaruppiah 

we are following the TSC adopted policy https://github.com/opiproject/opi/blob/main/CONTRIBUTING.md#architecture-changes

only small trivial changes are merged with 1 review approval
Big architecture or Spec changes are waiting for at least 4 days and need at least 2 approvals

you can tag more reviewers in the comment I will check if I can add them to review list after you mention their names

2022-09-27 00:32 UTC, AnuradhaKaruppiah commented
> 



> > > > Thanks for sending the PR @jainvipin. The files in this commit upstream one vendor's NB. While they create a great starting point, merging this PR as-is without other vendors collaborating (committing to implement it or even reviewing it) in some fashion creates an unfair advantage to one vendor as it may now be perceived as "the" OPI NB.
> > > > To avoid that confusion and to use the content for what it is intended, as a discussion starting point, I will suggest moving the contents to a "Pensando" subdirectory. Once a collaborative NB is created based on the contributions from other OPI vendors and service providers it can be dropped into the main "cloud APIs". Do you think that would work?
> > > 
> > > 
> > > @AnuradhaKaruppiah We don't want to go down the path of vendor directories. That completely moves away from coming up with a common API.
> > 
> > 
> > @sandersms So far OPI has been using the approach of merge as soon as one reviewer acks (and it seemed like that was fulfilled on this PR) hence my comments. If the PR is going to be held open till folks have had a chance to review that may work. I am unable to add other reviewers to the PR, do I need some special perms for that.
> 
> @AnuradhaKaruppiah This is is significant contribution and we are holding this PR open for comment and discussion until 12 October 2022 and we will discuss on 13 Oct 2022 in the meeting. We have not approved nor merged this PR and comments and discussion continue. That is the rational for my additional statement for holding this PR open for continued discussion.

Ack; i saw the comment you just added.

2022-09-27 00:35 UTC, AnuradhaKaruppiah commented
> @AnuradhaKaruppiah
> 
> we are following the TSC adopted policy https://github.com/opiproject/opi/blob/main/CONTRIBUTING.md#architecture-changes
> 
> only small trivial changes are merged with 1 review approval Big architecture or Spec changes are waiting for at least 4 days and need at least 2 approvals
> 
> you can tag more reviewers in the comment I will check if I can add them to review list after you mention their names

@glimchb I would like @tmonjalo added along with Roni Bar Yanai and Erez Cohen (I am unable to tag them; I will get their handles after they are back from Rosh Hashanah/Yom Kippur)

2022-09-27 00:43 UTC, glimchb commented
@AnuradhaKaruppiah - @rbaryanai ?

2022-09-27 21:44 UTC, jainvipin commented
> > 
> 
> > > > > Thanks for sending the PR @jainvipin. The files in this commit upstream one vendor's NB. While they create a great starting point, merging this PR as-is without other vendors collaborating (committing to implement it or even reviewing it) in some fashion creates an unfair advantage to one vendor as it may now be perceived as "the" OPI NB.
> > > > > To avoid that confusion and to use the content for what it is intended, as a discussion starting point, I will suggest moving the contents to a "Pensando" subdirectory. Once a collaborative NB is created based on the contributions from other OPI vendors and service providers it can be dropped into the main "cloud APIs". Do you think that would work?
> > > > 
> > > > 
> > > > @AnuradhaKaruppiah We don't want to go down the path of vendor directories. That completely moves away from coming up with a common API.
> > > 
> > > 
> > > @sandersms So far OPI has been using the approach of merge as soon as one reviewer acks (and it seemed like that was fulfilled on this PR) hence my comments. If the PR is going to be held open till folks have had a chance to review that may work. I am unable to add other reviewers to the PR, do I need some special perms for that.
> > 
> > 
> > @AnuradhaKaruppiah This is is significant contribution and we are holding this PR open for comment and discussion until 12 October 2022 and we will discuss on 13 Oct 2022 in the meeting. We have not approved nor merged this PR and comments and discussion continue. That is the rational for my additional statement for holding this PR open for continued discussion.
> 
> Ack; i saw the comment you just added.

thanks @AnuradhaKaruppiah @sandersms @glimchb for chiming in.
IMHO - there is nothing vendor specific in the APIs i.e. the concepts, functionality, relationship, object hierarchy etc. are very generic. In fact, I had to take out vendor specific things from the API before making it a community proposal. concepts and object relationship can be found in any cloud service provider's public documentation (e.g. VPC, subnet, etc.) and the object structure is inspired by K8s - easily understood by people.

2022-09-30 16:45 UTC, jainvipin commented on network/cloud-services/protos/ipsec.proto
> +  AUTHENTICATION_ALGORITHM_AES_CBC_SHA = 4;
@stevedoyle - it was assumed to be 256 (default), but I feel we should be having following specific choices choices.
- AUTHENTICATION_ALGORITHM_AES_CBC_SHA256
- AUTHENTICATION_ALGORITHM_AES_CBC_SHA384
- AUTHENTICATION_ALGORITHM_AES_CBC_SHA512
also pls note @pathreya

2022-09-30 16:45 UTC, jainvipin commented on network/cloud-services/protos/ipsec.proto
> +  ENCRYPTION_ALGORITHM_DES3        = 9;
Ack!

2022-09-30 16:47 UTC, jainvipin commented on network/cloud-services/protos/ipsec.proto
> +  AUTHENTICATION_ALGORITHM_HMAC        = 3;
AES and HMAC hashs are different, as mentioned in the comment below both of the algorithms can be enumeraged with 256, 384 and 512 bits

2022-09-30 16:48 UTC, jainvipin commented on network/cloud-services/protos/ipsec.proto
> +  uint64                  Iv                      = 10;
let's hear if anyone objects to taking IV out; if no objections, we can remove it.

2022-09-30 16:49 UTC, jainvipin commented on network/cloud-services/protos/ipsec.proto
> +  IpsecProtocol           Protocol                = 2;
I am good with removing AH all together; independently we can decide to keep AH+ESP or not; I am good with not keeping that option (at least for now)

2022-09-30 16:58 UTC, AnuradhaKaruppiah commented on network/cloud-services/README.md
> +Cloud Service APIs define the objects to manage cloud infrastructure APIS that could be offered by an xPU. These APIs are expected to be called by a cloud controller (definition of which is out of sc
A few high level questions -
1. Can you please include a figure to demonstrate where this layer would sit in the layer cake (there are several examples of the networking layer cake [here](https://github.com/opiproject/opi-api/tree/main/doc/images ). What goes above and below?
2. How would this interact with different verticals (Openstack/OVN, OVN-Kubernetes, SDN i.e. NOS in a DPU container) that have networking infra?
3. Networking for better or worse is settled tech and there are a lot of APIs already out there. If any of the APIs in this PR where derived from an existing model it will be good to indicate the source. That way we can assess the effort level involved with having application providers start over with a new model.

2022-09-30 17:34 UTC, jainvipin commented on network/cloud-services/protos/mirror.proto
> +message MirrorRuleSpec {
ah got it - so `MirrorPolicy` is a set of ordered set of rules each being a `MirrorRule` - so in a way the order is important because it gives absolute priority to certain traffic to be mirrored different from the other. Then one can modify the order independent (via MirrorPolicy) to be different from the MirrorRule itself.

2022-09-30 21:41 UTC, jainvipin commented on network/cloud-services/README.md
> +Cloud Service APIs define the objects to manage cloud infrastructure APIS that could be offered by an xPU. These APIs are expected to be called by a cloud controller (definition of which is out of sc
@AnuradhaKaruppiah - some answers here.

>1. Can you please include a figure to demonstrate where this layer would sit in the layer cake (there are several examples of the networking layer cake [here](https://github.com/opiproject/opi-api/tree/main/doc/images). What goes above and below?

The layering is cutting at the proto layer defined in https://github.com/opiproject/opi-api/blob/main/doc/images/Config-API-Boundary.png and perhaps how grpc is used in https://github.com/opiproject/opi-api/blob/main/doc/images/API-GW-Layers.png

On top of this is a multi-tenant cloud control plane managing cloud workloads and network services (e.g. a multi-tenant K8s CNI for VMs/Containers, Openstack for VMs/BMs, or a closed source control plane). Below the gRPC layer is an implementation (e.g. DPDK based network datapath acceleration available with the xPU capabilities). So as in the picture the layer below would interact with vendor SDK to achieve the xPU specific acceleration.

> 2. How would this interact with different verticals (Openstack/OVN, OVN-Kubernetes, SDN i.e. NOS in a DPU container) that have networking infra?

It integrates well with different control plane entities such as Openstack via Neutron plugin, leveraging the  APIs/concepts like VPCs, network services (LB, stateful ACLs, etc.), and network SDN virtualization. Similarly, a k8s CNI can map the  k8s objects such as NetworkPolicy, Services, Networks (aka virtual networks) and namespaces mapping to VPCs, etc. I see a natural fit on the concepts, in fact all of them are seeking similar functions from DPUs, the one I listed in here.

>  3. Networking for better or worse is settled tech and there are a lot of APIs already out there. If any of the APIs in this PR where derived from an existing model it will be good to indicate the source. That way we can assess the effort level involved with having application providers start over with a new model.

These APIs are a culmination of what is offered by private/public cloud providers and solutions:
https://docs.openstack.org/api-ref/network/v2/index.html
https://github.com/Azure/DASH/tree/main/documentation/gnmi (see examples)
https://docs.oracle.com/en-us/iaas/Content/Network/Concepts/overview.htm
https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html

These are not the APIs for every domain but for cloud networking and cloud services.

Of course, as defined by the charter of the project, the goal is to not reinvent anything here that is well defined, just  expose the familiar concept by DPUs and allow the control plane to leverage the tech underneath.

2022-10-04 14:26 UTC, glimchb commented on network/cloud-services/README.md
> +Cloud Service APIs define the objects to manage cloud infrastructure APIS that could be offered by an xPU. These APIs are expected to be called by a cloud controller (definition of which is out of sc
@jainvipin this is super helpful !

2022-10-04 15:32 UTC, AnuradhaKaruppiah commented on network/cloud-services/README.md
> +Cloud Service APIs define the objects to manage cloud infrastructure APIS that could be offered by an xPU. These APIs are expected to be called by a cloud controller (definition of which is out of sc
Thanks for providing these references. I think this PR needs an arch review first. So maybe you can present the layers and end-to-end solution in one of the upcoming meetings?

I am not sure I got the part where these specs are already in use by providers. For e.g. is there an end-to-end OVN implementation where these APIs are in use? Redhat Openshift?

2022-10-04 22:13 UTC, jainvipin commented on network/cloud-services/README.md
> +Cloud Service APIs define the objects to manage cloud infrastructure APIS that could be offered by an xPU. These APIs are expected to be called by a cloud controller (definition of which is out of sc
> I am not sure I got the part where these specs are already in use by providers. For e.g. is there an end-to-end OVN implementation where these APIs are in use? Redhat Openshift?

2022-10-06 12:49 UTC, rbaryanai commented on network/cloud-services/README.md
> +# Cloud Services APIs
in general, I think this is quite a big change to digest. even that building blocks are known
 the final model looks like a fixed e2e solution.

2022-10-06 14:33 UTC, tmonjalo commented
Thank you for the huge contribution.
I see there are multiple comments and I expect more details have to be discussed.
I feel it will be difficult to converge all these discussions with a single patch.
And honestly it is quite difficult to digest so many concepts at once.
Would it be easier to split this work in smaller patches with proper explanations of the design in each patch?
I think we would progress more efficiently if discussing features one by one in separate patches, merging them in a logical order, starting with the most basic features.
Opinions?

2022-10-06 16:55 UTC, jainvipin commented on network/cloud-services/protos/debug.proto
> +}
packet buffer (or pb) is a generic thing I felt, but happy to take it out. let's hear what others have to say about this.

2022-10-06 17:02 UTC, jainvipin commented on network/cloud-services/protos/debug.proto
> +}
these are generic api to get table stats - on demand for debugging purposes. the way object structure is defined, it could be applicable to any table in the datapath. Again, if this feels implementation specific, I am happy to take it out.

2022-10-06 17:04 UTC, jainvipin commented on network/cloud-services/protos/debug.proto
> +}
generic - one can query the table details by table name. let's discuss the relevance of this and generality of this.

2022-10-06 17:08 UTC, jainvipin commented on network/cloud-services/protos/policer.proto
> +}
agree - adding type will allow for reusing the concepts.

2022-10-06 17:09 UTC, AnuradhaKaruppiah commented on network/cloud-services/README.md
> +Cloud Service APIs define the objects to manage cloud infrastructure APIS that could be offered by an xPU. These APIs are expected to be called by a cloud controller (definition of which is out of sc
I missed this comment before today's meeting i.e. that this PR is not relevant to OVN/OVS. We can continue the discussion on where it is relevant and how to consume it after you have had the chance to present the arch next week.

2022-10-06 17:11 UTC, jainvipin commented on network/cloud-services/protos/policer.proto
> +
sure - a type would allow differentiating the two, as per the previous comment.

2022-10-06 17:13 UTC, jainvipin commented on network/cloud-services/protos/meter.proto
> +  uint32         MeterClass = 3 [(gogoproto.moretags) = "meta:range:1-4095"];
ack, we can leave it as uint32 in the API and have different APIs on the device limits/capabilities. if you want to propose the capabilities API that'd be helpful.

2022-10-06 17:15 UTC, jainvipin commented on network/cloud-services/README.md
> +The APIs covers various aspects of a functional xPU in cloud deployment, ranging from the device configuration to network datapath and control protocols.
as discussed in the offline meeting, let's classify the objects that are common, and work on them at different directories.

2022-10-06 17:18 UTC, jainvipin commented
> Thank you for the huge contribution. I see there are multiple comments and I expect more details have to be discussed. I feel it will be difficult to converge all these discussions with a single patch. And honestly it is quite difficult to digest so many concepts at once. Would it be easier to split this work in smaller patches with proper explanations of the design in each patch? I think we would progress more efficiently if discussing features one by one in separate patches, merging them in a logical order, starting with the most basic features. Opinions?

Ack; it is a big PR - but a complete PR. i.e. one would be good with these protos to implement the cloud-infrastructure network and network services.

however to address the concern, as discussed in the opi-api meeting, we will split this PR into multiple sub components and discuss it independently.

2022-10-06 17:20 UTC, jainvipin commented on network/cloud-services/README.md
> +# Cloud Services APIs
@rbaryanai  - ack; pls see my comment below on  the completeness and a proposal on having smaller splits.

2022-10-06 17:22 UTC, jainvipin commented on network/cloud-services/protos/meter.proto
> +  uint32 LPMBlockId          = 2 [(gogoproto.jsontag) = "LPMBlockId"];
It was meant to be a collection of LPM entries to be looked at as a whole for metering.
I will remove it, given that it is specific to an implementation.

2022-10-06 21:02 UTC, jainvipin commented on network/cloud-services/protos/meter.proto
> +  types.IPPrefix Prefix       = 1;
So metering is typically for a given tenant's workload i.e. this would be src-ip if the traffic for traffic originated by the tenant and dest-ip for traffic destined to the tenant's workload. I took liberty in calling it `Prefix` and use it interpretively based on the direction.

2022-10-06 23:56 UTC, jainvipin commented on network/cloud-services/protos/meter.proto
> +  uint32 PoolId              = 1 [(gogoproto.jsontag) = "PoolId"];
the pool could indicate a grouping a prefix belongs, the pool information itself can be obtained using `MeterPolicyPoolGet`, use of metering pools can allow managing the policy in aggregate manner. If this is not desired, we can take it out. Let's hear what if others have any opinion

2022-10-07 08:45 UTC, lmilleri commented on network/cloud-services/README.md
> +- VPC: Virtual Private Cloud is the key concept in network virutalization, refrering to a seggregated (from other tenants) networks defining overlapping subnets, routes, interfaces, service mappings,
some typos: virutalization, refrering, seggregated

2022-10-10 18:27 UTC, jainvipin commented on network/cloud-services/README.md
> +- VPC: Virtual Private Cloud is the key concept in network virutalization, refrering to a seggregated (from other tenants) networks defining overlapping subnets, routes, interfaces, service mappings,
@lmilleri - thanks!
fixed.

2022-12-08 14:31 UTC, mestery approved these changes
Hi folks, this has been sitting here for a long while now. I think this PR addresses the common use case of using a DPU or IPU for cloud infrastructure from a networking perspective. I propose we merge this and begin to iterate on this PR. We can always change things as we go. But moving networking forward would be nice at this point.

2022-12-08 14:50 UTC, rbaryanai commented
> Hi folks, this has been sitting here for a long while now. I think this PR addresses the common use case of using a DPU or IPU for cloud infrastructure from a networking perspective. I propose we merge this and begin to iterate on this PR. We can always change things as we go. But moving networking forward would be nice at this point.

Hi Kyle, there were a lot of comments , were they addressed, I didn't see version two or maybe I'm not a reviewer for that.

2022-12-08 15:23 UTC, mestery commented
> > Hi folks, this has been sitting here for a long while now. I think this PR addresses the common use case of using a DPU or IPU for cloud infrastructure from a networking perspective. I propose we merge this and begin to iterate on this PR. We can always change things as we go. But moving networking forward would be nice at this point.
> 
> Hi Kyle, there were a lot of comments , were they addressed, I didn't see version two or maybe I'm not a reviewer for that.

@jainvipin, can you address any remaining comments on this so we can merge this one and move forward?

Note that we're not saying this is the *only* networking API for OPI, we're saying it solves a common use case, and we believe it can be implemented across all the vendor IPU and DPU devices however they want underneath.

2022-12-08 16:13 UTC, rbaryanai commented
> > > Hi folks, this has been sitting here for a long while now. I think this PR addresses the common use case of using a DPU or IPU for cloud infrastructure from a networking perspective. I propose we merge this and begin to iterate on this PR. We can always change things as we go. But moving networking forward would be nice at this point.
> > 
> > 
> > Hi Kyle, there were a lot of comments , were they addressed, I didn't see version two or maybe I'm not a reviewer for that.
> 
> @jainvipin, can you address any remaining comments on this so we can merge this one and move forward?
> 
> Note that we're not saying this is the _only_ networking API for OPI, we're saying it solves a common use case, and we believe it can be implemented across all the vendor IPU and DPU devices however they want underneath.

not clear to me. a process of review is when the author address comments, some times it is just a reply and sometimes it is a required changed. here there were many such comments including clearly vendor internal ones that need to be changed. if there is going to be per vendor API for cloud then fine.

2022-12-08 17:43 UTC, mestery commented
> > > > Hi folks, this has been sitting here for a long while now. I think this PR addresses the common use case of using a DPU or IPU for cloud infrastructure from a networking perspective. I propose we merge this and begin to iterate on this PR. We can always change things as we go. But moving networking forward would be nice at this point.
> > > 
> > > 
> > > Hi Kyle, there were a lot of comments , were they addressed, I didn't see version two or maybe I'm not a reviewer for that.
> > 
> > 
> > @jainvipin, can you address any remaining comments on this so we can merge this one and move forward?
> > Note that we're not saying this is the _only_ networking API for OPI, we're saying it solves a common use case, and we believe it can be implemented across all the vendor IPU and DPU devices however they want underneath.
> 
> not clear to me. a process of review is when the author address comments, some times it is just a reply and sometimes it is a required changed. here there were many such comments including clearly vendor internal ones that need to be changed. if there is going to be per vendor API for cloud then fine.

To be clear, I understand how pull requests work.

However, note that this is not a vendor specific API, we're literally trying here to enable a use case (DPU and IPU devices for cloud infra). I expect @jainvipin will address the remaining comments above as we look to drive this forward to a state where we can merge it. Note that we also need a working reference implementation of this, which will take some time to implement as well.

Given that the networking APIs are stuck in stasis in OPI, I'm just trying to help move something forward here, with a use-case based approach, rather than the kitchen sink approach which seems to be popular for these types of things.

2023-09-07 16:23 UTC, jainvipin commented
closing this pr in favor of the work that has gone in-parts to the cloud apis; thanks everyone for the review, comments and support

2023-09-07 16:23 UTC, closed without merging