nvme initiator protos
opiproject/opi-api pull request #133
Opened 2022-09-23 20:29 UTC by jainvipin

Signed-off-by: Vipin Jain <jainvipin@gmail.com>

Wanted to throw out the initiator protos to start the discussion. Tested the protoc compilation (and generation of pb.go files) from protoc (after emoving --lint) in the Makefile, all looks good there. but following pending
1. proto linting; move from CamelCase to under_score syntax; minor but required change
2. most importantly, need to merge the NVMe protos in the frontend, middleend, and backend hierarchy as it exists today

let's discuss what fits best for our needs and I will submit subsequent changes on #3 above
cc @glimchb @sandersms

2022-09-25 17:01 UTC, glimchb requested changes
@jainvipin this is excellent
as agreed, we will work together to break this commit into several chunks and merge into existing APIs !
appreciate the contribution

2022-09-26 19:10 UTC, jainvipin commented
> @jainvipin this is excellent as agreed, we will work together to break this commit into several chunks and merge into existing APIs ! appreciate the contribution

sounds good! I fixed lint errors in the meanwhile and verified all code generation is looking good. let's discuss on the merge!

2022-09-27 00:22 UTC, glimchb commented
@orendu and @GottliebNoam , please review this once the official holidays are over and you back in the office

2022-09-28 17:59 UTC, glimchb commented
@jainvipin 

I think we can start with merging proposed `storage/proto/NvmeControllerPci.proto` 
into `NVMeControllerService` from https://github.com/opiproject/opi-api/blob/main/storage/proto/frontend-nvme-pcie.proto 

I see 
```
service NvmeControllerSvc {
  // Instantiate a new controller on the given PCI-ID
  rpc NvmeControllerCreate (NvmeControllerCreateRequest) returns (NvmeControllerCreateResponse) {}
  // Enable a namespace attached to the controller
  rpc NvmeControllerEnableNs (NvmeControllerEnableNsRequest) returns (NvmeControllerEnableNsResponse) {}
  // Disable a namespace attached to the controller
  rpc NvmeControllerDisableNs (NvmeControllerDisableNsRequest) returns (NvmeControllerDisableNsResponse) {}
  // Get controller information
  rpc NvmeControllerGet (NvmeControllerGetRequest) returns (NvmeControllerGetResponse) {}
  // Delete a controller
  rpc NvmeControllerDelete (NvmeControllerDeleteRequest) returns (NvmeControllerDeleteResponse) {}
}
```
vs
```
service NVMeControllerService {
    rpc NVMeControllerCreate (NVMeControllerCreateRequest) returns (NVMeControllerCreateResponse) {}
    rpc NVMeControllerDelete (NVMeControllerDeleteRequest) returns (NVMeControllerDeleteResponse) {}
    rpc NVMeControllerUpdate (NVMeControllerUpdateRequest) returns (NVMeControllerUpdateResponse) {}
    rpc NVMeControllerList   (NVMeControllerListRequest)   returns (NVMeControllerListResponse)   {}
    rpc NVMeControllerGet    (NVMeControllerGetRequest)    returns (NVMeControllerGetResponse)    {}
    rpc NVMeControllerStats  (NVMeControllerStatsRequest)  returns (NVMeControllerStatsResponse)  {}
}
```

sounds reasonable ? WDYT ?

2022-09-28 18:53 UTC, glimchb commented on storage/proto/CommonTypes.proto
> +// expose multiple devices with one physical function each and one or more
there are few places mentioning `DSC` specifically

2022-09-28 19:00 UTC, jainvipin commented on storage/proto/CommonTypes.proto
> +// expose multiple devices with one physical function each and one or more
Ack.

2022-09-28 19:07 UTC, glimchb commented on storage/proto/NvmeControllerPci.proto
> +  rpc NvmeControllerEnableNs (NvmeControllerEnableNsRequest) returns (NvmeControllerEnableNsResponse) {}
I'm thinking about `NvmeControllerEnableNs` and `NvmeControllerDisableNs` now...
do they belong to the `NvmeControllerSvc` or to the `NvmeNamespacePciSvc` ?

2022-09-28 19:08 UTC, glimchb commented
I see `storage/proto/NvmeControllerPci.proto` and `storage/proto/NvmeNamespacePci.proto` to the HOST, but where is `storage/proto/NvmeSubsystemPci.proto` ?

2022-10-04 18:40 UTC, llabordehpe commented
@jainvipin : two questions about your API:
- Why are the object handles assigned by the client? How is the client suppoed to know what is OK for an opaque handle? Considering that the OPI API is supposed to work will all vendors/IPUs, I think the opaque handle has to be assigned by the provider.
- Why is there a field "types.ApiStatus  api_status" in your protobuf response messages ? Don't you get your operation status from the gRPC status codes ?

2022-10-04 18:51 UTC, glimchb commented on storage/proto/NvmeTargetPort.proto
> +// target port service
this looks more like target APIs and not Initiator APIs, true ?

2022-10-04 18:52 UTC, glimchb commented on storage/proto/NvmeTargetSubsys.proto
> +service NvmeTargetSubsystemSvc {
this looks more like target APIs and not Initiator APIs, true ?

2022-10-04 21:50 UTC, jainvipin commented on storage/proto/NvmeTargetSubsys.proto
> +service NvmeTargetSubsystemSvc {
this is the target configuration on the Initiator, so you can say these are target (or back-end) APIs based on how you have divided the APIs to be front-end, middle-end, and the back-end in your classification.

2022-10-04 21:51 UTC, jainvipin commented on storage/proto/NvmeTargetPort.proto
> +// target port service
I am calling all these initiator APIs because of where these APIs are implemented, but the target port is a configuration on the Initiator.

2022-10-04 22:12 UTC, jainvipin commented
> @jainvipin : two questions about your API:
> 
> * Why are the object handles assigned by the client? How is the client suppoed to know what is OK for an opaque handle? Considering that the OPI API is supposed to work will all vendors/IPUs, I think the opaque handle has to be assigned by the provider.
> * Why is there a field "types.ApiStatus  api_status" in your protobuf response messages ? Don't you get your operation status from the gRPC status codes ?

@llabordehpe - appreciate your observation on this. The way I see, there are two ways of uniquely identifying an object. 1) based on the key fields (e.g. target-ip, port, etc.), in this case a handle is assigned by the provider. 2) based on a handle e.g. name or uuid (which is also a special type of string), provider can still return its own handle in this case as well, but can use the name/uuid provided by the client to organize its lookups. The benefit of second approach is that it can differentiate the instances of two objects with same key fields as two instances of an object, since the uuids can change but key fields would be same. e.g. if we want to introduce (target-ip,port) as unique set of fields and would like to introduce tenant-id, or sub-systemid later we can do that without altering the semantics of the APIs.

Also, given that `Spec` fields can change and evolve, in these APIs we preferred going with approach #2, so we have flexibility to evolve the APIs without changing the uniqueness semantics. Use of UUID is not too uncommon to identify a object instance. K8s APIs for example use a name to uniquely identify an object, which can be a uuid string if instance uniqueness is required.

In either cases, backend implementation is easier if it uses an id/handle based lookup than searching on the key fields. So the current APIs have a unique `[] byte` opaque key field for various objects.

2022-10-05 11:09 UTC, jkogutINTC commented on storage/proto/NvmeIniDev.proto
> +  // (mandatory) unique NQN identifer for the host, used in fabric connect to
Is it really the same NQN identified exposed to host which is used in connection to the NVMe-oF target?

2022-10-05 11:09 UTC, jkogutINTC commented on storage/proto/NvmeIniDev.proto
> +// initiator device service
it will be nice to have short overview in comment what it is "Nvme iniaiator device"? It is a description how the device will be exposed to host?

The same comment is for other introduced ne definitions in the review.

2022-10-05 11:09 UTC, jkogutINTC commented on storage/proto/NvmeIniDev.proto
> +// Nvme iniaiator device proto specification
spelling iniaiator -> initiator

2022-10-05 16:28 UTC, glimchb commented on storage/proto/NvmeTargetSubsys.proto
> +service NvmeTargetSubsystemSvc {
I thought that `storage/proto/NvmePath.proto` is  back-end (network facing APIs)...

2022-10-05 17:40 UTC, glimchb commented on storage/proto/CommonTypes.proto
> +// expose multiple devices with one physical function each and one or more
+1. should be called `DPU/IPU`

2022-10-05 21:08 UTC, jainvipin commented on storage/proto/CommonTypes.proto
> +// expose multiple devices with one physical function each and one or more
sure, will call it xPU

2022-10-05 21:14 UTC, jainvipin commented on storage/proto/NvmeIniDev.proto
> +// Nvme iniaiator device proto specification
fixed

2022-10-06 06:55 UTC, orendu commented on storage/proto/CommonTypes.proto
> +// virtual functions under the physical function.
+1
B:D:F already defines any PCI function, physical or virtual.
Not clear what is the purpose of this virtual_function field.

2022-10-06 07:11 UTC, orendu commented on storage/v1/NvmeNamespacePci.proto
> +service NvmeNamespacePciSvc {
What is the meaning of "Pci" in all the names related to namespace management?
A namespace is an NVMe object (of a subsystem) unrelated to PCI or any other transport...

2022-10-06 07:20 UTC, orendu commented on storage/v1/CommonTypes.proto
> +  // Physical function, always set to 0 in current model
Comment about always set to 0 should be removed, it is vendor choice.

2022-10-06 07:28 UTC, orendu commented on storage/v1/NvmeNamespacePci.proto
> +  bool               auto_connect         = 4;
In the layering we discussed for OPI, this should be part of the backend APIs, not the frontend.
I.e., in SPDK, when NVMe-oF connection is created to a remote subsystem, bdevs are created as a result. This is the right place to indicate auto_connect, and retry_interval.

2022-10-06 07:29 UTC, orendu commented on storage/v1/NvmeNamespacePci.proto
> +  uint64             num_blocks           = 2;
This should probably be taken from the backend object assigned to this namespace.

2022-10-06 07:29 UTC, orendu commented on storage/v1/NvmeNamespacePci.proto
> +message NvmeNamespacePciParams {
Missing a reference to the backend object representing the backend volume assigned to this namespace.

2022-10-06 07:34 UTC, orendu commented on storage/v1/NvmeNsCrypto.proto
> +service NvmeNsCryptoSvc {
According to OPI storage API layering, crypto should be part of the middle-end APIs.
i.e., take any backend volume object (created by backend API), define crypto on top of it (middle-end API), then use the result in a frontend NVMe namespace or virtio-blk volume (frontend APIs).

2022-10-06 07:47 UTC, orendu commented
Could we see an example flow of expected calls to this API that will eventually set up a remote NVMe-oF namespace as a local PCI NVMe controller and namespace?

It will help understanding the full picture.

I suspect that some of the APIs here belong to backend APIs. NvmeTargetSubsys (if I got it correctly), NVMeTargetPort, NvmePath - are they all to define a connection (with multipath) to remote storage target? If so, they belong to the backend APIs.

Crypto should be middle-end.

Missing the concept of a subsystem in the frontend (with multiple controllers and namespaces in it).

2022-10-06 08:11 UTC, orendu commented on storage/v1/CommonTypes.proto
> +// virtual functions under the physical function.
An xPU may also expose one device with multiple physical functions...

2022-10-06 08:12 UTC, orendu commented on storage/v1/CommonTypes.proto
> +  uint32 virtual_function  = 4;
As pointed in another comment, the triplet {bus:device:function} is enough to describe both virtual and physical functions. What is the need for this additional field?

2022-10-06 11:23 UTC, intelfisz commented
> Could we see an example flow of expected calls to this API that will eventually set up a remote NVMe-oF namespace as a local PCI NVMe controller and namespace?
> 
> It will help understanding the full picture.
> 
> I suspect that some of the APIs here belong to backend APIs. NvmeTargetSubsys (if I got it correctly), NVMeTargetPort, NvmePath - are they all to define a connection (with multipath) to remote storage target? If so, they belong to the backend APIs.
> 
> Crypto should be middle-end.
> 
> Missing the concept of a subsystem in the frontend (with multiple controllers and namespaces in it).

Thanks @orendu for pointing it out. This is exactly my point - for such a comprehensive commit we need at least some high-level architecture and/or usage examples - can you provide that @jainvipin? @glimchb can you elaborate on the expected main clients in the [Common APIs abstraction layer](https://github.com/opiproject/opi-api/tree/main/storage#common-apis-abstraction-layer)? I assume K8s nodes.

2022-10-06 13:12 UTC, glimchb commented on storage/v1/NvmeNamespacePci.proto
> +service NvmeNamespacePciSvc {
I guess this is NVMe/PCI emulation presented to the host, this is why Pci is here...

2022-10-06 13:18 UTC, glimchb commented
> Missing the concept of a subsystem in the frontend (with multiple controllers and namespaces in it).
@orendu I also pointed this to @jainvipin 
he answered me privately, maybe he can paste his answer here as well...

2022-10-06 13:21 UTC, glimchb commented
> @glimchb can you elaborate on the expected main clients in the [Common APIs abstraction layer](https://github.com/opiproject/opi-api/tree/main/storage#common-apis-abstraction-layer)? I assume K8s nodes.

@intelfisz  one of the clients can be k8s via csi. we track this work here https://github.com/opiproject/goopicsi and here https://github.com/opiproject/opi-api/blob/main/storage/opi-csi.md

But we also have other orchestrators, non k8s based that can send the commands to configure many of DPU/IPUs in the datacenter.

2022-10-06 15:20 UTC, jainvipin commented on storage/v1/NvmeNamespacePci.proto
> +service NvmeNamespacePciSvc {
Host facing is named suffixed with `pci`

2022-10-06 15:34 UTC, jainvipin commented on storage/proto/NvmeIniDev.proto
> +  // (mandatory) unique NQN identifer for the host, used in fabric connect to
all host exposed fields are in `NvmeControllerPci` object, therefore this nqn is used to identiy the device to connect to the NVMe-oF target (which would have configured to accept connections from this nqn)

2022-10-06 15:36 UTC, jainvipin commented on storage/v1/CommonTypes.proto
> +  // Physical function, always set to 0 in current model
ack, will fix.

2022-10-06 15:46 UTC, jainvipin commented on storage/v1/NvmeNamespacePci.proto
> +  uint64             num_blocks           = 2;
configuring this here can allow an abstraction of showing different size. we can make this optional - would that work?

2022-10-06 15:51 UTC, jainvipin commented on storage/v1/NvmeNamespacePci.proto
> +  bool               auto_connect         = 4;
let's discuss; auto-connect is meant to allow the namespace to be primed before NvmeController is enabled on the host - this is specific to namespace not the backend config (path/subsystem objects in this PR), which is shared by multiple namespaces and thus not controllable per namespace. This PR doesn't have a bdev backend object, and so.

2022-10-06 16:04 UTC, jainvipin commented
> Could we see an example flow of expected calls to this API that will eventually set up a remote NVMe-oF namespace as a local PCI NVMe controller and namespace?

yes, will document example flow. 

> It will help understanding the full picture.
> 
> I suspect that some of the APIs here belong to backend APIs. NvmeTargetSubsys (if I got it correctly), NVMeTargetPort, NvmePath - are they all to define a connection (with multipath) to remote storage target? If so, they belong to the backend APIs.

yes there are backend, frontend and middleend apis as part of this PR - but for NVMe.

> Crypto should be middle-end.
> 
> Missing the concept of a subsystem in the frontend (with multiple controllers and namespaces in it).

@glimchb also made this observation. we have the configuration in the controller object, and subsystem nqn is included there too. However, we can keep the subsystem hierarchy explicitly.

2022-10-06 16:04 UTC, jainvipin commented
> @orendu @intelfisz @jainvipin we can definitely take this PR and split in smaller pieces and review and merge them... I already did one small chunk here #134

sounds like a good idea. we'll submit smaller consumable PRs out of comments in this PR and go with that.

2022-10-06 17:50 UTC, llabordehpe commented
> 

@jainvipin: The general gRPC error handling (https://grpc.io/docs/guides/error/), and particularly the richer error model (https://cloud.google.com/apis/design/errors#error_model) should have everything you need to convey errors to the client, without defining new status/error fields in your protobuf response messages.

2022-10-06 22:53 UTC, yadong2007 commented
> 

Hi, there is an interesting proposal.  It enables discussions.
After I took a quick look at the proposal, I feel it's hard for me to understand the exact level of abstraction this proposal tries to achieve.  A few comments and questions:
- First, it's not clear what exactly the "Client" that you are trying to enable.  If it's K8s CSI node driver, then exposing a lot of details in NVMe subsystem and NVMe controllers do not help simplify anything.  It will be good to clear state the "client", and then drive top level API definitions from there.
- Second, it's also not clear what exactly the Vendor SDK or IPU/DPU SDK you are trying to enable.  If it's SPDK implementation, then a lot of the APIs in this proposal seems duplicate or similar to SPDK JSON RPCs.
- To make the bridge/shim API defined properly, I think we need start with a "Client" and a "IPU/DPK SDK".  To make sure it works at least for one of such clients.
- I also highly recommend splitting the API definition for different usages,  "Initiator" vs "Target".  The APIs for Initiators can be highly simplified.  The Target API is often tied to vendor specific storage server design, it will take time to get to a standard based API definition.

2022-10-06 23:23 UTC, glimchb commented
@yadong2007 did you look at the existing already merged APIs https://github.com/opiproject/opi-api/tree/main/storage/v1 ?
also check out OPI-SPDK bridge we built https://github.com/opiproject/opi-poc/tree/main/storage/server
also check CSI library we building https://github.com/opiproject/goopicsi based on https://github.com/opiproject/opi-api/blob/main/storage/opi-csi.md

2022-10-06 23:51 UTC, yadong2007 commented
> @yadong2007 did you look at the existing already merged APIs https://github.com/opiproject/opi-api/tree/main/storage/v1 ? also check out OPI-SPDK bridge we built https://github.com/opiproject/opi-poc/tree/main/storage/server also check CSI library we building https://github.com/opiproject/goopicsi based on https://github.com/opiproject/opi-api/blob/main/storage/opi-csi.md

@glimchb Hi Boris, thanks for the links.  I remember these patches.  It's a very good starting point. 
I like the architecture diagrams in this page: https://github.com/opiproject/opi-api/blob/main/storage/opi-csi.md  I think it's more effective to illustrate the key API call sequences using CSI node driver as an example client.   Basically adding a few sequence diagrams will make it clear what the exact APIs exposed to the CSI node driver and to the CSI controller driver in the management node.

2022-10-07 01:11 UTC, glimchb commented
@yadong2007 I agree. can you help out and create some sequence diagrams so we can review them ?

2022-10-07 15:19 UTC, yadong2007 commented
> @yadong2007 I agree. can you help out and create some sequence diagrams so we can review them ?

Hi Boris, yes, Intel team is working on the sequence diagrams.  Will share whenever it's ready in next couple of weeks.

2022-10-07 15:57 UTC, glimchb commented
> > @yadong2007 I agree. can you help out and create some sequence diagrams so we can review them ?
> 
> Hi Boris, yes, Intel team is working on the sequence diagrams. Will share whenever it's ready in next couple of weeks.

I created one here, let me know what you think https://github.com/opiproject/opi-poc/pull/387/files

2022-10-11 13:22 UTC, intelfisz commented on storage/proto/CommonTypes.proto
> +// virtual functions under the physical function.
@pwalessi-dell this also needs to be aligned here: https://github.com/opiproject/opi-api/blob/main/storage/v1/common.proto

2022-10-14 04:51 UTC, jainvipin commented
> > 
> 
> @jainvipin: The general gRPC error handling (https://grpc.io/docs/guides/error/), and particularly the richer error model (https://cloud.google.com/apis/design/errors#error_model) should have everything you need to convey errors to the client, without defining new status/error fields in your protobuf response messages.

@llabordehpe - I understand grpc is very flexible on what error codes can return; however we were unable to capture the details e.g. Nvme specific fields/values to be returned alongwith details to referring objects and transport layer is not capturing it. Would it not allow us to keep better flexibility and debuggability better for NVMe layer if we have a verbose status reponse?

2022-10-14 04:53 UTC, jainvipin commented on storage/proto/NvmeTargetSubsys.proto
> +service NvmeTargetSubsystemSvc {
yes, will move these to backend protos @glimchb in a separate PR for backend objects.

2022-10-14 04:57 UTC, jainvipin commented on storage/proto/NvmeControllerPci.proto
> +  bytes  fru_guid           = 5;
@jkogutINTC - are you suggesting we change the name to FGUID or the size to be specific, the idea was that bytes would cover this to be 16bytes value.

2022-10-14 05:01 UTC, jainvipin commented on storage/v1/NvmeNamespacePci.proto
> +message NvmeNamespacePciParams {
@orendu - will put a diagram to explain the backend objects a bit, but it is indirectly referenced through path objects.

2022-10-14 05:03 UTC, jainvipin commented on storage/v1/NvmeIniDev.proto
> +service NvmeIniDevSvc {
@orendu this is the initiator personality (nqn) to identify itself to the backend

2022-10-14 05:03 UTC, jainvipin commented on storage/v1/CommonTypes.proto
> +// virtual functions under the physical function.
hmm... haven't heard of this use case; @glimchb @llabordehpe - any comments on this use case?

2022-10-14 05:04 UTC, jainvipin commented on storage/v1/CommonTypes.proto
> +  uint32 virtual_function  = 4;
@orendu - let me get back on this one and update this comment later

2022-10-14 05:12 UTC, jainvipin commented
@yadong2007 - some reponses inline..
 
> Hi, this is an interesting proposal. It enables discussions. After I took a quick look at the proposal, I feel it's hard for me to understand the exact level of abstraction this proposal tries to achieve. A few comments and questions:
> 
> * First, it's not clear what exactly the "Client" that you are trying to enable.  If it's K8s CSI node driver, then exposing a lot of details in NVMe subsystem and NVMe controllers do not help simplify anything.  It will be good to clearly state the "client", and then drive top level API definitions from there.

The client is really a configurator of the Nvme devices on the DPU; it doesn't even need to be residing on the host e.g. BM provisioning will keep this API to be called from over the cloud infrastructure network. Having said that,  this can be used by a CSI driver in k8s deployment to provision volumes and bind mount them into pods as they get scheduled on nodes.

> * Second, it's also not clear what exactly the Vendor SDK or IPU/DPU SDK you are trying to enable.  If it's SPDK implementation, then a lot of the APIs in this proposal seems duplicate or similar to SPDK JSON RPCs.

The backend of these APIs could be SPDK or a P4 implementation. The reason to propose these APIs is to have the flexibility to use different implementations for various platform and capabilities.

> * To make the bridge/shim API defined properly, I think we need start with a "Client" and a "IPU/DPU SDK".  To make sure it works at least for one of such clients.
Of course. The APIs are going to be  (or have already been) vetted against a working implementation.

> * I also highly recommend splitting the API definition for different usages,  "Initiator" vs "Target".  The APIs for Initiators can be highly simplified.  The Target API is often tied to vendor specific storage server design, it will take time to get to a standard based API definition.

Good point; I will change this; this is creating a good amount of confusion to many reviewers.

2022-10-16 07:38 UTC, orendu commented on storage/v1/NvmeNamespacePci.proto
> +  bool               auto_connect         = 4;
So you mean this is a flag indicating that a specific namespace must be present before the controller is exposed to the host?
For example, a controller is made of two namespaces, and one of them does not exist at the moment (remote is down, for instance).  If the flag is set - enabling the controller will be blocked, and if it is unset, enabling the controller with be allowed and the missing namespace won't be presented?
If this is a correct description, then maybe the flag should be named "mandatory" or alike...

2022-10-16 07:46 UTC, orendu commented on storage/v1/NvmeNamespacePci.proto
> +  uint64             num_blocks           = 2;
yes, it could act as some kind of "override" to the properties of the underlying backend. block_size could also potentially be changed...
Also consider, its may be natural to explain what happens if the override reduces the total capacity of the backend volume, but what happens if it increases it?

2022-10-17 23:48 UTC, glimchb commented on storage/v1/NvmeIniDev.proto
> +service NvmeIniDevSvc {
is this equivalent to https://spdk.io/doc/jsonrpc.html#rpc_nvmf_subsystem_add_host ?

2022-10-19 14:14 UTC, mkalderon commented on storage/v1/CommonTypes.proto
> +// virtual functions under the physical function.
@orendu , @jainvipin aren't you referring to the same ? multi-function devices ? 
@jainvipin what do you mean by xPU exposes mutiple devices - don't you mean multiple pfs ?

2022-10-19 14:15 UTC, mkalderon commented on storage/v1/CommonTypes.proto
> +  // Physical function, always set to 0 in current model
maybe has to do with mutli-function device discussed above, but xPU could expose several PFs where Function won't be 0

2022-10-21 04:07 UTC, glimchb commented on storage/v1/NvmeNamespacePci.proto
> +  types.ObjectKey    controller_key       = 2;
in dual ported NVMe drives you have 1 subsystem with 2 controllers... 
and NSID is attached to controllers either privately or shared between multiple controllers... 
no ?

![see](https://github.com/opiproject/opi-api/blob/main/doc/images/nvme-sub-ctrl-ns.png?raw=true)

2022-10-21 04:07 UTC, glimchb commented on storage/v1/NvmeNamespacePci.proto
> +  // (mandatory) Initiator device for the namespace, corresponding initiator
+1

2022-10-21 14:14 UTC, benlwalker commented on storage/v1/NvmeNamespacePci.proto
> +  types.ObjectKey    controller_key       = 2;
Correct that's the only case where they're not 1:1 for a local PCIe SSD. If we feel it is necessary to be able to model that in an xPU we can discuss that. But I doubt we need to.

2023-09-07 16:22 UTC, jainvipin commented
closing this pr in favor of the work that has gone in-parts to the storage apis; thanks everyone for the review, comments and support

2023-09-07 16:22 UTC, closed without merging