storage: Unify front-end block APIs
opiproject/opi-api pull request #171
Opened 2022-10-24 17:43 UTC by benlwalker

This is a new proposed starting point for a unified set of front-end block APIs can that can work for virtio-blk, NVMe, and NVMe-oF. To be clear right up front, I'm not even certain that I agree with all of these decisions or approve of this set of APIs. But I think it's a good starting point.

What I tried to accomplish here was to unify the front-end APIs but keep the front-end/middle-end/back-end concept in the current OPI model. I've personally been arguing that we need to instead batch these APIs into fewer endpoints for atomicity reasons, but I think at least conceptually the front/middle/back concept is here to stay.

The most important concepts here are as follows:

1) I'm unifying not only exposing an NVMe or virtio-blk device to a host system, but also exposing an NVMe-oF device over the network (so the network is the front end bus).

2) I've introduced a generic "Device" which for NVMe is equivalent to a subsystem.

3) I've introduced the concept of an endpoint. For NVMe/PCIe, this is a controller at some BDF. For other types, it can be re-used and the controller is a more dynamic and short-lived thing.

4) The PCI stuff does not allow the endpoint to specify the BDF. It only lets you pick the PF/VF ids. The BDF is assigned by the OS PCI driver and we cannot pick it in these APIs.

Signed-off-by: Ben Walker <benjamin.walker@intel.com>

2022-10-26 07:54 UTC, mkalderon commented
Hi @benlwalker 
Few general questions: 
1. trying to understand nvme-of frontend. We have a network-device that once reaches the DPU, the storage commands are lost, we just have tcp / rdma packets, how will the DPU be able to intercept and provide middle / end services ? Or do you see the DPU in this case terminating the connection and establishing another ? more details on the use case and flow would be great. thanks.
3. again, would be great for a more specific example - do you see other use cases that will define an endpoint other than controller bdf which are not nvme-of ? 
thanks

2022-10-26 11:04 UTC, glimchb commented
> Hi @benlwalker Few general questions:
> 
> 1. trying to understand nvme-of frontend. We have a network-device that once reaches the DPU, the storage commands are lost, we just have tcp / rdma packets, how will the DPU be able to intercept and provide middle / end services ? Or do you see the DPU in this case terminating the connection and establishing another ? more details on the use case and flow would be great. thanks.
> 2. again, would be great for a more specific example - do you see other use cases that will define an endpoint other than controller bdf which are not nvme-of ?
>    thanks

I think the intent for TCP is to terminate NVMe/TCP connection from the Host and start and new one to the remote storage...
Whether it is useful for production or not - not for me to say, but it demonstrates the concept of having something in addition to PCIe well. not all vendors have to implement it... I would guess Virtio-blk will be added to this Device APIs...

I will let @benlwalker correct me if my understanding is wrong...

2022-10-26 14:41 UTC, benlwalker commented
We've so far only discussed the use of an xPU to offload the initiator side. The TCP endpoint I have in this proposal is instead to offload the target side, where the front-end NVMe host is over the network and the backend storage is attached to the xPU or to the host server the xPU is attached to. I included it primarily to get everyone thinking about a broader set of use cases.

2022-10-26 14:57 UTC, mkalderon commented
> We've so far only discussed the use of an xPU to offload the initiator side. The TCP endpoint I have in this proposal is instead to offload the target side, where the front-end NVMe host is over the network and the backend storage is attached to the xPU or to the host server the xPU is attached to. I included it primarily to get everyone thinking about a broader set of use cases.

thanks for the clarification

2022-10-27 17:25 UTC, glimchb requested changes
Following the online discussion today, the PR will change to keep the original naming specific for NVMe

2022-10-27 18:44 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    string nqn = 2;
local PCI NVMe devices do not need a subsystem NQN

2022-10-27 19:18 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
>      // maximum Number of namespaces that will be provisioned under
+1 for adding clarification @jainvipin @mkalderon @orendu WDYT ?

2022-10-27 19:22 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> -    // subsystem information
Don't you need to specify which Subsystem this CTRL belongs if you many multiple Subsystems...?

2022-10-27 19:22 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey subsystem_id = 2;
Don't you need to specify which Subsystem this NS belongs if you many multiple Subsystems...?

2022-10-27 19:24 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey subsystem_id = 1;
can you list all NSs in the specific subsystem ?

2022-10-27 19:25 UTC, glimchb commented on storage/v1/frontend_virtio_blk.proto
>  }
is there a `model_number` in virtio ?

2022-10-27 19:27 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> -    uint32 host_nsid = 4;
I think, we need to be able to set NSID, same as you did below with LUN_ID...

2022-10-27 19:34 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> -    int64 block_size = 5;
Not sure I agree... 
for example see https://www.mankier.com/1/nvme-format#--block-size
we able to change block size programmatically...
not sure we need middle layer just to do this...
will let others to chime in @mkalderon @jainvipin @orendu

2022-10-27 19:35 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> -    int64 num_blocks = 6;
same as above... plus I'm thinking AIO bdev from file to block... where we specify size? do we need split-like middle end just for this ?

2022-10-27 19:36 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey crypto_key_id = 10;
+1 `volume_id` below seems like a more generic name

2022-10-27 19:38 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> -    uint32 host_nsid = 4;
I see now... 
you moved it to `NVMeNamespaceCreateRequest` like `uint32 nsid = 3;`

2022-10-27 19:39 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> -    // subsystem information
I see now... you moved it to `NVMeControllerCreateRequest`

2022-10-27 19:40 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey subsystem_id = 2;
I see now... you moved it to `NVMeNamespaceCreateRequest`

2022-10-27 19:41 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> +    common.v1.ObjectKey subsystem_id = 2;
```suggestion
    // The subsystem to associate this controller with
    common.v1.ObjectKey subsystem_id = 2;
```

2022-10-27 20:24 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    int64 block_size = 5;
What you linked sends an NVMe format command. That's sent by the host system/user of the device to change the block size, which is very different than this administrative step. A format command would flow through the front-end all the way to the back end and change the block size there.

Emulating block sizes is not at all simple. For example:

- Emulating 4K blocks on top of 512 physical blocks has to deal with NVMe's atomicity guarantees, which cannot be less than 1 block.
- Emulating 512 byte blocks on top of 4K physical requires read/modify/write.

This is very much not just setting a number. It's a ton of logic to do this correctly. It cannot appear as a parameter here..

2022-10-27 20:26 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey subsystem_id = 1;
I wasn't entirely sure how to do these "list" commands for namespaces. You can do it several different ways:

1) List all the namespaces in a subsystem
2) List all the namespaces in a subsystem visible to a particular host (i.e. through a specific controller)
3) List all namespaces globally

I don't have a preference.

2022-10-27 20:32 UTC, benlwalker commented on storage/v1/frontend_virtio_blk.proto
>  }
I don't believe so. Now that I look I don't think it even has a serial number. This is what the 1.2 spec says is reported to the host:

```
struct virtio_blk_config { 
        le64 capacity; 
        le32 size_max; 
        le32 seg_max; 
        struct virtio_blk_geometry { 
                le16 cylinders; 
                u8 heads; 
                u8 sectors; 
        } geometry; 
        le32 blk_size; 
        struct virtio_blk_topology { 
                // # of logical blocks per physical block (log2) 
                u8 physical_block_exp; 
                // offset of first aligned logical block 
                u8 alignment_offset; 
                // suggested minimum I/O size in blocks 
                le16 min_io_size; 
                // optimal (suggested maximum) I/O size in blocks 
                le32 opt_io_size; 
        } topology; 
        u8 writeback; 
        u8 unused0; 
        u16 num_queues; 
        le32 max_discard_sectors; 
        le32 max_discard_seg; 
        le32 discard_sector_alignment; 
        le32 max_write_zeroes_sectors; 
        le32 max_write_zeroes_seg; 
        u8 write_zeroes_may_unmap; 
        u8 unused1[3]; 
        le32 max_secure_erase_sectors; 
        le32 max_secure_erase_seg; 
        le32 secure_erase_sector_alignment; 
};
```

2022-10-27 20:32 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey subsystem_id = 1;
we can do all 3...
- if client provided subsystem parameter -> List all the namespaces in a subsystem
- if client provided subsystem and controller parameters -> List all the namespaces in a subsystem only visible to specific controller
- if no parameters -> List all the namespaces globally

WDYT ?

2022-10-27 20:34 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    int64 num_blocks = 6;
Well you'd create a back-end volume, and if you were creating an AIO volume backed by a file you could specify the size there.

2022-10-27 20:46 UTC, glimchb commented
@llabordehpe for some reason can't add you to reviewers list, so tagging you here. please review

2022-10-27 20:53 UTC, glimchb commented on storage/v1/frontend_virtio_blk.proto
missing
```
import "object_key.proto";
```

2022-10-27 20:53 UTC, glimchb commented on storage/v1/frontend_virtio_scsi.proto
missing
```
import "object_key.proto";
```

2022-10-27 21:12 UTC, llabordehpe commented on storage/v1/frontend_virtio_scsi.proto
> +    uint32 result = 1;
Why do we need a result field?

2022-10-27 21:13 UTC, llabordehpe commented on storage/v1/frontend_virtio_scsi.proto
> +    uint32 result = 1;
Why do we need a result field?

2022-10-27 21:16 UTC, llabordehpe commented on storage/v1/frontend_nvme_pcie.proto
> +    int64 max_ns = 4;
Is there a reason why max_ns is type int64 in NVMeSubsystem, and type uint32 in NVMeController ?

2022-10-27 22:14 UTC, benlwalker commented on storage/v1/frontend_virtio_scsi.proto
> +    uint32 result = 1;
Just matches the NVMe equivalent now. I don't have an opinion.

2022-10-27 22:15 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> +    int64 max_ns = 4;
Copied from NVMe. But even there I think it should only be 16 bit.

2022-10-27 22:46 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> +    int64 max_ns = 4;
there is no 16 bit in grpc... :-(

2022-10-27 22:49 UTC, glimchb commented on storage/v1/frontend_virtio_scsi.proto
> +    uint32 result = 1;
in a separate PR we will replace all return values according to https://google.aip.dev/133

2022-10-28 22:29 UTC, glimchb commented on storage/v1/frontend_virtio_scsi.proto
> +    uint32 result = 1;
opened #174 to track it after this PR merged

2022-10-31 09:17 UTC, mkalderon commented on storage/v1/frontend_nvme_pcie.proto
> -    string nqn = 2;
- perhaps a unify/non-unify question, but if we use the same message for nvme-oF we will need the nqn, not worth having just one struct ? 
- NQN is still provided in the response of get ctrl info, perhaps we want to enable control for what this response will be

2022-11-01 05:59 UTC, jainvipin commented
> 

Would the frontend APIs look same for what's needed on the initiator vs. target?

2022-11-01 06:00 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> +    int64 max_ns = 4;
should it be uint32 then, instead of int64?

2022-11-01 06:44 UTC, jainvipin requested changes
@benlwalker - good to see various services combined for Nvme, Virtio etc. together. Some comments on the structural changes here; will provide nvme specific comments subsequently.

2022-11-01 06:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey subsystem_id = 2;
Well if we want to keep the REST semantics - there are resources and then there are CRUD operations on them (using POST/PUT/GET/etc.). This allows all the information about resource to be fully kept in the resource itself. Moving subsystem reference out of the resource and putting in context of the create request will not keep the APIs as RESTful. The disadvantages could be:
- user intent is captured outside the resource definition i.e. a GET on an object may not reveal what was created. It is not a good design, usually someone should be able to do GET on all objects to reconstruct the entire configured intent.
- you need yet another mechanism to describe this relationship e.g. which subsystem a namespace corresponds to.
- Mixing actions with resource can set precedence of doing this for other fields too. Ref: https://en.wikipedia.org/wiki/Restful_Objects
- Breaking the assumptions can also make plenty of tooling around REST APIs unusable.

I'd suggest re-considering this decision and keeping NVMeSubsystem, NVMeController and NVMeNamespaces as resources that user can configure, including any relationships between them is specified through those object definitions. Please see any popular open source project (e.g. K8s object definitions) for reference.

2022-11-01 06:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> -    uint32 host_nsid = 4;
same comment as for subsystem_id, let's keep this field here.

2022-11-01 06:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey crypto_key_id = 10;
for some reason. I don't see that change, can we keep this field as
```
common.v1.ObjectKey services_keychain_id

2022-11-01 06:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> +    common.v1.ObjectKey subsystem_id = 2;
suggest removing contextual information in REST actions.

2022-11-01 06:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> +    common.v1.ObjectKey subsystem_id = 2;
suggest removing contextual information in REST actions.

2022-11-01 06:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> +    uint32 nsid = 3;
suggest removing contextual information in REST actions.

2022-11-01 06:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey subsystem_id = 1;
Although I don't have a strong opinion on this. Usually List() APIs don't provide filter parameters, but if we do the semantics of filtering can be tricky e.g. find me with `A || B` or `A && B` or `(A && B) || C`. I know we want to keep things simple, but that's the most generic way of doing List filtering. I am okay if we enumerate common field(s) but still the interpretation of those fileds (togher) will be some implicit  semantic (i.e.. AND or OR operation) - which is not a good thing.

2022-11-01 06:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> +service FrontendNvme {
+1 on combining these multiple services into one on various objects - it is just too much to have to deal with them separatelly.

2022-11-01 21:09 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey subsystem_id = 2;
The reason I changed it was because the previous code did not correctly capture all of the complexities of the possible relationships. My new approach does. But I understand your points here as well. Here's some of the possible issues with how it was done before:

1) If we ever want to support dispersed namespaces, then a namespace can be in more than one subsystem. That means the it can't hold just one subsystem_id.
2) Namespaces can be visible through more than one controller, so the namespace can't have just one controller_id.
3) A namespace can exist at different NSIDs for different controllers (and in different subsystems if we support dispersed namespaces)

How would you propose we solve these issues? Making the user fill out the entire list of relationships any time they want to make a call is not convenient at all.

2022-11-01 21:12 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey crypto_key_id = 10;
I think @glimchb and I are very much saying no, we cannot keep it as anything related to crypto. Is there a reason you absolutely must get the crypto information right here, and not get it by looking at the associated volume backing this namespace?

2022-11-01 21:18 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey crypto_key_id = 10;
I don't think @jainvipin disagrees, he is just not seeing the change on github from all the comments...
@benlwalker changed
```
    // reference to encryption key for the data at rest encryption
    common.v1.ObjectKey crypto_key_id = 10;
```
to
```
    // The back/middle-end volume to back this namespace.
    common.v1.ObjectKey volume_id = 5;
```

2022-11-02 05:44 UTC, jainvipin requested changes
@benlwalker - thanks for the PR; some comments inline if we can agree to those!

2022-11-02 05:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> -    string nqn = 2;
if we remove nqn here how would host see a subsystem. @chaitanyahuilgol - any comments?

2022-11-02 05:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> -    string firmware_revision  = 6;
ack - we could remove this from here; however it is a good candidate for why we need to resolve #180 to remove this from spec and put in status.

2022-11-02 05:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> -    // subsystem information
`subsystem_id` that a controller refers to should be in the `NVMeController` object for keeping resource definitiosn wholesome (i.e. an Nvmecontroller is not defined properly if it doesn't refer to a subsystem)

2022-11-02 05:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey subsystem_id = 2;
ok I understand your point of view; can we deal with it using one of the following ways:
1. Create another namespace, attach to a different subsystem_id, but have the same `guid` for both. This could be done in the proposed APIs without any changes.
2. Alternatively. one can make subsystem_id a list within a `Namespace` object and so user can configure various subsystem it would need to correspond.

For example, k8s captures 1:n relationship typically by having a list of named references or selection (m:n) references.

2022-11-02 05:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
>      // maximum Number of namespaces that will be provisioned under
We use it for what you mentioned here - it helps allocate appropriate resources. So I'd not say `less flexible` but `optimized resource allocater` :-)

2022-11-02 05:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey controller_id = 3;
let's not remove named references out of object resources.

2022-11-02 05:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> -    int64 block_size = 5;
well if `block_size` is presented to the host for a block device, then shouldn't frontend should have this value? @chaitanyahuilgol any comments?

2022-11-02 05:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> -    int64 num_blocks = 6;
well if you are virtualizing a block device, this is really a frontend parameter that user should configure on what to expose.

2022-11-02 05:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey crypto_key_id = 10;
I am good with keeping it `volume_id` and have crypto and middleend fields in that. Then `volume_id` really is a refrerence to middle_end object handle that contains various parameters for crypto/etc.

2022-11-02 05:44 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> -    uint32 optimal_write_size = 11;
Per spec, xPU exposes this value to the driver for optimal writes, so this would be a configuration to XPU. @chaitanyahuilgol - any comments? Btw, @benlwalker - are you suggesting these fields move to a backend object that a frontend object refers to but ultimately provided to the driver using the value in the referred backend object?

2022-11-02 05:49 UTC, jainvipin commented
> We've so far only discussed the use of an xPU to offload the initiator side. The TCP endpoint I have in this proposal is instead to offload the target side, where the front-end NVMe host is over the network and the backend storage is attached to the xPU or to the host server the xPU is attached to. I included it primarily to get everyone thinking about a broader set of use cases.

@benlwalker - I am curious if the changes you made were exclusively for Target side (or Initiator side as well)? Of course the endpoint object is not really there.

2022-11-02 11:11 UTC, chaitanyahuilgol commented on storage/v1/frontend_nvme_pcie.proto
> -    string nqn = 2;
The nqn provided here is intended to be reported in the identify controller response - SUBNQN field. @benlwalker can you please let us know what are the alternatives for getting the SUBNQN if not provided here?

2022-11-02 14:27 UTC, mkalderon commented on storage/v1/frontend_nvme_pcie.proto
>      // maximum Number of namespaces that will be provisioned under
We see this as NN value. true that current mainstream drivers don't use the NN value. But there are some bios drivers which look at this value. There could be a use-case where host boots from nvme-device using such bios drivers.

2022-11-02 16:44 UTC, benlwalker commented on storage/v1/common.proto
> -    uint32 bus              = 1;
How does the xPU pick the bus number? I'm fairly certain it's picked by the OS PCI driver.

2022-11-02 16:44 UTC, benlwalker commented on storage/v1/common.proto
> -    uint32 device           = 2;
We do not want to preclude any topology. Multiple PFs with multiple VFs must be supported. My change isn't modifying that requirement, it's just acknowledging that the xPU can't control what BDF it's devices show up at entirely - they're picked by the OS PCI driver.

2022-11-02 16:44 UTC, benlwalker commented on storage/v1/common.proto
> +    uint32 physical_id = 1;
Sure

2022-11-02 16:44 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    string nqn = 2;
There is no consumer of the SUBNQN value for a local NVMe device as far as I'm aware. The xPU can generate a value to fill that field in with. Did you have a particular use case where this is used and must be configured by the administrator?

(My comments do not apply to NVMe-oF where this is definitely needed)

2022-11-02 16:44 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    string firmware_revision  = 6;
I think I understand what you're getting at. I was treating this object as an INPUT from the client. But this object is pulling double-duty as both an input and an output. I think we need to resolve the lack of clarity on that as part of #180. I'll comment there.

2022-11-02 16:44 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    // subsystem information
In this case yes, the controller always refers to exactly one subsystem so we could leave this id if we really wanted to maintain the relationship encoding in the objects.

2022-11-02 16:44 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
>      // maximum Number of namespaces that will be provisioned under
You should absolutely not use NN for resource provisioning. You shouldn't use it at all. I suspect it won't be entirely uncommon for NN to be set to the maximum value, to allow an unknown number of namespaces to be added or removed from a subsystem in the future. You cannot change NN without a reset, so most implementations should err on the side of going very large here.

Both the Linux kernel drivers and the SPDK drivers have been burned by this and have had very deep discussions around NN. The result of those discussions is do not use NN for anything, especially provisioning resources. We cannot re-introduce this mistake to OPI.

2022-11-02 16:44 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    int64 block_size = 5;
I would see it as a major design flaw if we have parameters on the front-end that the user has to fill out that only exist to be validated against an automatic calculation based on the back-end volume. That's just adding unnecessary complexity for the user of this API.

This number cannot be an input from the user during the front-end configuration.

2022-11-02 16:44 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    int64 num_blocks = 6;
We should allow that flexibility, either creating a middle-end API to truncate an arbitrary volume, or by allowing it to be configured directly in the back-end. But it cannot go here.

2022-11-02 16:44 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    uint32 optimal_write_size = 11;
I am suggesting that this configuration be done when creating the back-end/middle-end objects, which are what actually dictate these values. The front-end just reports them via the NVMe interfaces.

2022-11-03 05:59 UTC, jainvipin commented on storage/v1/common.proto
> -    uint32 bus              = 1;
I am agreeing that this is not set by xPU. that's why it is reported (in `Status`) by what is seen by xPU, not configured/set by xPU.

2022-11-04 06:52 UTC, chaitanyahuilgol commented on storage/v1/frontend_nvme_pcie.proto
> -    string nqn = 2;
@benlwalker we can make this optional. but we should keep it around, we should give the client flexibility to configure this if they choose to

2022-11-04 06:57 UTC, chaitanyahuilgol commented on storage/v1/frontend_nvme_pcie.proto
>      // maximum Number of namespaces that will be provisioned under
IMO, this also qualifies for an optional parameter, we should not enforce any particular implementation by not allowing  this configuration. If clients want to provide and/or xPU want to use this, then it should be available.

2022-11-06 15:16 UTC, mkalderon commented on storage/v1/frontend_nvme_pcie.proto
>      // maximum Number of namespaces that will be provisioned under
> IMO, this also qualifies for an optional parameter, we should not enforce any particular implementation by not allowing this configuration. If clients want to provide and/or xPU want to use this, then it should be available.

agree

2022-11-07 19:46 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    string nqn = 2;
As we're headed now, we likely will not unify front-end NVMe-oF with this.

2022-11-07 19:46 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    string nqn = 2;
Do you or does anyone have any use case for this? Again, the drivers do not even look at it. I'm trying to understand the motivation for wanting it. If there's some reason to have it I'm not at all opposed, but let's please provide reasons for things to exist in this API or we'll end up adding everything in the entire specification.

2022-11-07 19:46 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
>      // maximum Number of namespaces that will be provisioned under
NN is the maximum namespace id allowed, not the maximum number of namespaces attached. For example, you can support 4 namespaces with a maximum namespace ID value of 1000. Those namespaces can be at nsid 0, 12, 569, and 985.

We need these things to be documented very clearly. If this is NN, no implementation should use this value to do any internal resource provisioning. Lots of users are going to set this to MAXUINT16 or whatever the max is, and rightly so. There are some BIOS and other "broken" (old, really) NVMe drivers that use NN for namespace enumeration, so it does of course make sense to expose devices with NN values that are far smaller as well.

I believe we should really have two configuration values. The maximum NSID (NN) and the maximum number of namespaces. Both can be optional.

2022-11-07 19:46 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    common.v1.ObjectKey subsystem_id = 2;
I suspect this is going to simplify after #187 because the "list" of associated controllers (and maybe subsystems) will actually be in the status, not the spec.

2022-11-14 19:40 UTC, closed without merging