Split CQ/SQ and add max queue entries
opiproject/opi-api pull request #175
Opened 2022-10-28 11:25 UTC by amarv-marvell

1) As per spec multiple submission queues may utilize the same completion queue.
   Hence decoupling the two.
2) Submission queues and completion queues can have different depths.
Will push poc updates once poc changes for Vipin's request are uploaded.

Signed-off-by: Amar Vishwakarma <amarv@marvell.com>
Signed-off-by: Michal Kalderon <mkalderon@marvell.com>

2022-10-28 12:39 UTC, glimchb commented
@benlwalker @llabordehpe @jkogutINTC @intelfisz @GottliebNoam please review

2022-10-28 12:41 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> +    uint32_t max_nsq = 5;
```
frontend_nvme_pcie.proto:85:5: "uint32_t" is not defined.
frontend_nvme_pcie.proto:90:5: "uint32_t" is not defined.
frontend_nvme_pcie.proto:93:5: "uint32_t" is not defined.
frontend_nvme_pcie.proto:96:5: "uint32_t" is not defined.
```
please fix

2022-10-28 12:42 UTC, glimchb requested changes
failed CI, please fix `uint32_t`

2022-10-28 13:54 UTC, glimchb reviewed
Thanks for the fixes, looks much better now.

Don't forget to run `make` and commit the generated files as well. this is why CI failing...

2022-10-28 14:20 UTC, amarv-marvell commented on storage/v1/frontend_nvme_pcie.proto
> +    //maximum submission queue entries; given as index of 2
done

2022-10-28 14:20 UTC, amarv-marvell commented on storage/v1/frontend_nvme_pcie.proto
> +    uint32_t max_nsq = 5;
fixed

2022-10-28 14:20 UTC, amarv-marvell commented
> 

done

2022-10-28 19:13 UTC, benlwalker requested changes

2022-10-28 19:13 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> +    // maximum submission queue depth; given as index of 2
Do you mean power of 2?

2022-10-28 19:21 UTC, amarv-marvell commented on storage/v1/frontend_nvme_pcie.proto
> +    // maximum submission queue depth; given as index of 2
yes. corrected!

2022-10-28 19:49 UTC, benlwalker requested changes

2022-10-28 19:49 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> -    // maximum host IO queue pairs allowed, value will default to
Only because these comments end up becoming the public documentation, I'm going to be very pedantic for a moment. In several places there is phrasing like this:

> value will default to limits in PCI device configuration; if set to 0 or more it will default to maximum permitted per xPU's capability

You didn't write that initially, but in this patch you do propagate that to several new values. That phrasing doesn't make any sense though, so let's fix it. I suggest:

> If not set, the xPU will provide a default.

2022-10-28 19:49 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> +    // maximum number of host completion queues allowed, value will default to
Similarly here, I'd suggest:

> Maximum number of host completion queues allowed. Optional. If not set, the xPU will provide a default.

2022-10-28 19:49 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> +    // maximum submission queue depth; given as power of 2
There's actually some subtlety to this. It should not say "queue depth", it really should say:

> Maximum number of submission queue entries per submission queue, as a power of 2.

This is not the same as queue depth because NVMe allows devices to consume off of the submission queue without reporting a completion immediately. So you can theoretically have a higher total queue depth of outstanding commands than entries in the submission queue. Very few devices actually work this way, but some really do.

2022-10-28 19:49 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> +    // maximum completion queue depth; given as power of 2
The completion queue side is simpler, but for consistency with the submission side I think we should write

> Maximum number of completion queue entries per completion queue, as a power of 2.

2022-10-28 20:46 UTC, jainvipin reviewed
LGTM

2022-10-28 22:26 UTC, glimchb commented
@benlwalker good proposals on comments, agree that since this is going to be our public documentation, make sense to fix those to be as clear and as correct as possible, thanks for your time reviewing this and thanks for suggesting the alternative language. will be easy for @amarv-marvell to fix!

2022-10-31 02:59 UTC, amarv-marvell commented on storage/v1/frontend_nvme_pcie.proto
> +    // maximum completion queue depth; given as power of 2
done.

2022-10-31 02:59 UTC, amarv-marvell commented on storage/v1/frontend_nvme_pcie.proto
> +    // maximum submission queue depth; given as power of 2
done.

2022-10-31 02:59 UTC, amarv-marvell commented on storage/v1/frontend_nvme_pcie.proto
> +    // maximum number of host completion queues allowed, value will default to
done.

2022-10-31 02:59 UTC, amarv-marvell commented on storage/v1/frontend_nvme_pcie.proto
> -    // maximum host IO queue pairs allowed, value will default to
done.

2022-10-31 03:00 UTC, amarv-marvell commented
> 

done.

2022-10-31 11:23 UTC, glimchb commented
@benlwalker give it a look and if ok, I will merge it today

2022-10-31 16:39 UTC, benlwalker approved these changes

2022-10-31 17:48 UTC, merged