[storage][front-end] Add google.api.http
opiproject/opi-api pull request #186
Opened 2022-11-02 21:43 UTC by glimchb

Following Google AIP-127 - HTTP and gRPC Transcoding

Related to #174

Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

2022-11-03 13:06 UTC, PWAlessi approved these changes
other than the url paths/names, looks good.

2022-11-03 13:08 UTC, PWAlessi requested changes
url paths and names need to change

2022-11-03 19:39 UTC, glimchb commented
> url paths and names need to change

fixed

2022-11-03 19:47 UTC, PWAlessi approved these changes
I'm not positive that this is correct because I've never implemented protobuf over REST/http. I'd say that if the proto compiler works, it's probably fine to merge. I'd also add a backlog item for building out (at least a mock) http server to see if it works as expected.

2022-11-03 19:50 UTC, glimchb commented
> I'm not positive that this is correct because I've never implemented protobuf over REST/http. I'd say that if the proto compiler works, it's probably fine to merge. I'd also add a backlog item for building out (at least a mock) http server to see if it works as expected.

opened #188 to track backlog item

2022-11-03 22:38 UTC, jainvipin reviewed
one comment @glimchb on the path hierarchy

2022-11-03 22:38 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> +            body: "subsystem"
Do we want to prefix the path with `nvme`, `virtio`, etc. i.e. instead of implicit assumptions we can keep the nvme path to `/v1/nvme/subsystems`,`/v1/nvme/controllers`, etc.
Also there is an assumption that backend/frontend/middle API objects wouldn't conflict here if we don't include that in the path. i.e. `/v1/nvme/frontend/subsystems` or `/v1/nvme/fe/subsystems` vs. `/v1/nvme/subsystems`

2022-11-03 22:38 UTC, jainvipin commented on storage/v1/frontend_virtio_blk.proto
> +            patch: "/v1/virtioblks"
inline with previous comment this could be `/v1/virtio/blocks`, etc. or `/v1/virtio/frontend/blocks`?

2022-11-03 22:39 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> +            body: "subsystem"
yes, that' good suggestion. Will fix it on follow-up PR! great

2022-11-04 00:06 UTC, llabordehpe commented
Shouldn't the objects "hierarchy" be part of the the URLs (like in this [example](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/endpoints/bookstore-grpc/http_bookstore.proto))?
For example, in NVMeControllerCreate, don't we want:
   post: "/v1/subsystems/{subsystem}/controllers"
   body: "controller"
instead of :
   post: "/v1/controllers"
   body: "controller"

2022-11-04 00:12 UTC, glimchb commented
> Shouldn't the objects "hierarchy" be part of the the URLs (like in this [example](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/endpoints/bookstore-grpc/http_bookstore.proto))? For example, in NVMeControllerCreate, don't we want: post: "/v1/subsystems/{subsystem}/controllers" body: "controller" instead of : post: "/v1/controllers" body: "controller"

Yes, it should. I just didn't want to overload this PR with hierarchy since it can lead to a heavy discussion on who is parent of who... I opened #188 to track the correct hierarchy fixes

2022-11-04 12:13 UTC, mestery approved these changes

2022-11-04 12:15 UTC, merged

2022-11-04 13:49 UTC, llabordehpe commented on storage/v1/frontend_nvme_pcie.proto
> +            patch: "/v1/subsystems"
I think it shoud have been:
   patch: "/v1/subsystems/{subsystem}"

2022-11-06 15:39 UTC, mkalderon commented
@glimchb late response. looks good.