add status fields to frontend objects
opiproject/opi-api pull request #187
Opened 2022-11-02 21:53 UTC by jainvipin

Separate Spec (user configuration) and Status (sytem state) fields - motivations defined/discussed in #180 
Pls review @glimchb @benlwalker @mkalderon 

Signed-off-by: Vipin Jain <jainvipin@gmail.com>

2022-11-02 21:57 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> +}
@jainvipin to youwant to add `PCI BDF` to `NVMeControllerStatus` here  ? to show the diff between `virtual/physical` (picked by DPU) and `BDF` (assigned by host)

2022-11-03 16:24 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> +}
How would the xPU know what PCI BDF it was assigned?

2022-11-03 16:34 UTC, benlwalker requested changes

2022-11-03 16:34 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
>      // subsystem for this namespace
block_size, num_blocks, optimal_write_size, preferred_write_granularity should be in status (or removed)

2022-11-06 09:07 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> +    string firmware_revision  = 1;
well - for some systems, the version of the datapath for storage (e.g. if using P4) may differ from the device's firmware revision and it may be a good to keep the firmware_revision of a subsystem to be separate from that of a device.

2022-11-06 09:33 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> +    bool   host_active = 1;
xPU would know this via driver (indirectly driver must be loaded) and controller is enabled.

2022-11-06 09:34 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
>      // subsystem for this namespace
Makes sense. we can remove these from spec and keep them in status. will update the PR.

2022-11-07 06:32 UTC, mkalderon commented
LGTM

2022-11-07 18:54 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> +    bool   host_active = 1;
How does the xPU know that the driver is currently loaded? The controller can certainly be left in an enabled state without a driver loaded against it.

2022-11-07 18:57 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> +    string firmware_revision  = 1;
So you're saying there's some abuse of the firmware version to indicate which datapath the device uses? Shouldn't that be purely a control-plane thing, where we can query that using OPI APIs about back/middle-end volumes? I'm still a -1 on having this here. It doesn't sound like the right way to solve the problem outlined.

2022-11-07 18:57 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> +    bool   host_active = 1;
Just to skip ahead in the discussion - you can't know that the host is active or that the driver is loaded from the xPU.

2022-11-07 19:21 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> +}
To jump ahead on this discussion point, you can't know what BDF you were assigned from the xPU.

2022-11-07 19:54 UTC, glimchb commented on storage/v1/frontend_nvme_pcie.proto
> +    bool   host_active = 1;
since @jainvipin have this in production, let's find out how they do it...

2022-11-07 20:15 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> +    string firmware_revision  = 1;
It is not abuse, it is a natural evolution of the programmability. And why should firmware only reflect control plane changes, it should including anything that can change the benavior. Technically even if a bit changes in the control/datapath it should have a different firmware so user know what version is being run.

In programmable datapath implementation where the device's firmware gets versioned/deployed independent of the storage datapath version/code (for that matter even for networking), we need to reflect that disjoint.

2022-11-07 20:27 UTC, benlwalker commented on storage/v1/frontend_nvme_pcie.proto
> +    string firmware_revision  = 1;
That's just not what the NVMe firmware revision means. This field means the version of the firmware on the device as a whole. This shouldn't change if you only change settings and configuration.

It seems to me like you want some way to query which particular configuration/data path is behind a front-end device, which is completely reasonable to do. But not using the NVMe firmware revision.

2022-11-07 21:02 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> +    bool   host_active = 1;
nvme driver updates the pcie config register as a controller is enabled (we call it `nvme_ctrlr::poll_ctrlr_reg_()`, and xPU polls for that value to reflect this in the status. I can get someone working on the driver team to chime in here; but this is how it works today and is a value to the cloud provider (or infra user). Certainly we can keep this optional.

2022-11-07 21:29 UTC, benlwalker approved these changes

2022-11-07 21:31 UTC, jainvipin commented on storage/v1/frontend_nvme_pcie.proto
> +    string firmware_revision  = 1;
well - we are looking at implementations where firmware does change dynamically - we can adopt it or ignore it.

2022-11-07 22:35 UTC, glimchb commented
I opened #191 but this is not blocking this PR

2022-11-08 05:52 UTC, mkalderon approved these changes

2022-11-08 13:34 UTC, PWAlessi approved these changes

2022-11-09 21:17 UTC, glimchb approved these changes

2022-11-09 21:18 UTC, merged