[storage] Rename NvmeControllerPciId to PciEndpoint
opiproject/opi-api pull request #190
Opened 2022-11-07 20:41 UTC by benlwalker

This is an important change. The OPI configuration APIs cannot pick the bus:device:function - that's assigned by the OS PCI driver. We can only pick the physical and virtual function numbers.

Signed-off-by: Ben Walker <benjamin.walker@intel.com>

2022-11-08 19:44 UTC, jainvipin requested changes
some comments inline @benlwalker

2022-11-08 19:44 UTC, jainvipin commented on storage/v1/common.proto
> -    uint32 bus              = 1;
we can add this to the status, perahps?

2022-11-08 19:44 UTC, jainvipin commented on storage/v1/common.proto
> -    uint32 device           = 2;
would prefer keeping this in, as some xPUs can offer multiple devices and user could allow selecting the device to offer this on. Note that there are multi-host deployment of xPUs and in some cases user can select exposing separate devices.

2022-11-08 20:07 UTC, PWAlessi commented on storage/v1/common.proto
> -    uint32 bus              = 1;
Is there a case where a user of the api needs the bus and device for some other functionality?

2022-11-08 20:48 UTC, benlwalker commented on storage/v1/common.proto
> -    uint32 bus              = 1;
There's a lot of cases where it would be useful, but it doesn't matter because the xPU doesn't know these values. They're assigned by the OS.

2022-11-08 20:49 UTC, benlwalker commented on storage/v1/common.proto
> -    uint32 bus              = 1;
How does the xPU know these values?

2022-11-08 20:49 UTC, benlwalker commented on storage/v1/common.proto
> -    uint32 device           = 2;
This change does not preclude multiple physical or virtual functions in any way.

2022-11-08 22:57 UTC, jainvipin commented on storage/v1/common.proto
> -    uint32 bus              = 1;
yes not generically - this may be the case only if you have trusted host. so we can ignore this comment if this is not generic enough to report BDF assigned by the host in the status.

2022-11-09 08:05 UTC, mkalderon approved these changes

2022-11-09 18:09 UTC, benlwalker commented
Updated after latest discussion on Slack. I think it may be interesting to return these in the status too, just for "discovery" purposes. And we need some way to discover what the valid values for an xPU are. But we can do those in separate PRs.

2022-11-09 18:35 UTC, glimchb commented on storage/v1/common.proto
> -    uint32 bus              = 1;
we might need a new BDF struct on the backend APIs if we want to attach local NVMe devices to DPU and expose them to host

2022-11-09 19:00 UTC, glimchb requested changes
committed `storage/googleapis/google/api/` by mistake @benlwalker ?

2022-11-09 19:04 UTC, glimchb approved these changes
see slack, agreement reached, merging this now

2022-11-09 19:04 UTC, merged