[storage] Add Crypto middle end volume
opiproject/opi-api pull request #208
Opened 2022-11-14 20:48 UTC by glimchb

Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

2022-11-15 15:35 UTC, glimchb commented
> Should the Crypto functionality be included in the middle end protobuf or should there be a separate common crypto capability that can be tied to the function (Storage, Security, Networking, etc.) that would create, delete, update, ... the capability?
> 
> Perhaps we can iterate on that aspect of the common functionality.

d@re (data at rest encryption) is only applicable for storage

we can definitely iterate on this common once we have another example that uses the same, we can easily move it around to a common place

2022-11-15 18:05 UTC, benlwalker requested changes

2022-11-15 18:05 UTC, benlwalker commented on storage/v1alpha1/middleend.proto
> +message Crypto {
Should we call it Crypto or CryptoVolume? Without the word "Volume" I think it leaves people room to misinterpret how this object really works. It's not the global crypto service, it's a specific volume (that may forward to another volume).

2022-11-15 18:55 UTC, glimchb commented on storage/v1alpha1/middleend.proto
> +message Crypto {
Sure, I can add the word `Volume` to it, I just have to do it across all RPCs as well

2022-11-15 20:15 UTC, glimchb commented on storage/v1alpha1/middleend.proto
> +message Crypto {
@jainvipin @orendu @mkalderon @llabordehpe what do you think about naming of this before I jump to change it ?

2022-11-15 22:25 UTC, llabordehpe commented on storage/v1alpha1/middleend.proto
> +    common.v1.ObjectKey volume_id = 1;
Which id is this one from Crypto struct? id or volume_id ? I assume it is id. Maybe we should rename it crypto_id (and same in GetCryptoRequest, CryptoStatsRequest, etc.. to remove ambiguity.

2022-11-15 22:31 UTC, glimchb commented on storage/v1alpha1/middleend.proto
> +    common.v1.ObjectKey volume_id = 1;
make sense. and WDYT about `Crypto` vs `CryptoVolume` proposal from @benlwalker on the struct name ?

2022-11-15 22:52 UTC, llabordehpe commented on storage/v1alpha1/middleend.proto
> +message Crypto {
How does this crypto object really work? After calling CreateCrypto(), can the original volume id still be used (in CreateNvmeNamespace for example), or should the new id be used ? And in term of calls order, what happens if you call CreateCrypto AFTER already using a volume with CreateNvmrNamespace ?

2022-11-15 23:07 UTC, glimchb commented on storage/v1alpha1/middleend.proto
> +message Crypto {
yes, layered services like SPDK. bdev on top of bdev and you can use either one of them

2022-11-15 23:39 UTC, glimchb commented on storage/v1alpha1/middleend.proto
> +message Crypto {
I will try to show the usage now, after I merge this and implement in our bridge example https://github.com/opiproject/opi-spdk-bridge/tree/main/server

2022-11-15 23:40 UTC, glimchb commented
opened #210 to think about better name, will try to implement now the code, to show the usage example

2022-11-15 23:40 UTC, merged

2022-11-16 16:59 UTC, jainvipin reviewed
some comments @glimchb

2022-11-16 16:59 UTC, jainvipin commented on storage/v1alpha1/middleend.proto
> +            post: "/v1/volumes"
the flat API structure is evident here `v1/volumes` is very generic, if we preceed it with `v1/middleend/volumes` that would decouple it from the backend volumes and overlap.

2022-11-16 16:59 UTC, jainvipin commented on storage/v1alpha1/middleend.proto
> +    bytes key = 3;
Is it a shared secret or a private key?

2022-11-16 16:59 UTC, jainvipin commented on storage/v1alpha1/middleend.proto
> +    bytes key = 3;
do we need to provide secret for `initial vector` or do we believe use of IV is perhaps a stale thing?

2022-11-16 16:59 UTC, jainvipin commented on storage/v1alpha1/middleend.proto
> +    string stats = 2;
same comment about stats as in other PRs

2022-11-16 16:59 UTC, jainvipin commented on storage/v1alpha1/middleend.proto
> +    Crypto volume = 1;
minor, why do we call the field `volume` it should be called `crypto`? e.g. what if we have other service applied on the volume, would that also be called `volume` in the create/update requests?

2022-11-16 17:02 UTC, glimchb commented on storage/v1alpha1/middleend.proto
> +            post: "/v1/volumes"
agree, part of #188

2022-11-16 17:03 UTC, glimchb commented on storage/v1alpha1/middleend.proto
> +    bytes key = 3;
no idea, this is just first draft, let's discuss

2022-11-17 12:54 UTC, intelfisz commented on storage/v1alpha1/middleend.proto
> +message Crypto {
@glimchb - encryption is a volume-level property. If we don't set it at volume creation timepoint (since this is middle-end API) then we need to make it clear in the documentation that CreateCrypto() should be called immediately after volume creation to avoid a data mess.

2022-11-17 14:16 UTC, glimchb commented on storage/v1alpha1/middleend.proto
> +message Crypto {
good point @intelfisz 

maybe we need an option to create crypto/compress/... basically all middle-end services together with the actual volume itself... documentation is nice, but often not enough. APIs should indeed encourage doing this somehow... 

maybe https://google.aip.dev/233 ? WDYT ?

2022-11-17 15:26 UTC, intelfisz commented on storage/v1alpha1/middleend.proto
> +message Crypto {
This is one of the reasons @benlwalker has been arguing for a higher abstraction level which we follow in SMA approach - either you split things into multiple calls (which may be used wrong way and require careful documentation/usage notes) or you just provide additional parameters to a single high-level call (like enabling crypto upon volume creation) which does it the proper way.

2022-11-17 16:15 UTC, benlwalker commented on storage/v1alpha1/middleend.proto
> +message Crypto {
Yes exactly. I think an alternative to SMA style big single calls is some sort of transaction manager service where all calls can be associated with a transaction and then committed at once. But you need one or the other.