Add Inventory protobuf in common area
opiproject/opi-api pull request #223
Opened 2022-12-12 20:34 UTC by sandersms

Starting point for Inventory protobuf for use in reporting the Device information.

2022-12-12 20:38 UTC, glimchb reviewed
it's a good start. I think we need to follow DMI (smbios) tables and define those messages:
- bios
- system
- baseboard
- chassis
- processor
- memory
and then return those 6 in the `InventoryGetResponse`

2022-12-12 20:38 UTC, glimchb commented on common/v1/inventory.proto
> +    DeviceInfo devinfo = 1;
I think we need to return 6 structs here:
- bios
- system
- baseboard
- chassis
- processor
- memory

2022-12-12 22:38 UTC, glimchb requested changes
can you please rebase? I think it will fail on several linters now

2022-12-13 02:39 UTC, glimchb commented on common/v1/inventory.proto
> +    rpc InventoryGet (InventoryGetRequest) returns (InventoryGetResponse) {}
according to https://google.aip.dev/131 rpc name should be `GetInventory`
according to https://google.aip.dev/131 rpc response should be just `Inventory`
example:
```
    rpc GetInventory (GetInventoryRequest) returns (Inventory)    {
        option (google.api.http) = {
            get: "/v1/{name=inventory}/{inventory}"
        };
        option (google.api.method_signature) = "name";
    }
```

2022-12-14 17:30 UTC, glimchb approved these changes

2022-12-14 17:31 UTC, sandersms commented on common/v1/inventory.proto
> +    rpc InventoryGet (InventoryGetRequest) returns (InventoryGetResponse) {}
Rebased and cleaned up the lint reported checks that are active.

2022-12-15 15:54 UTC, merged