document api extension methods
opiproject/opi-api pull request #224
Opened 2022-12-13 01:40 UTC by jainvipin

@sandersms @glimchb  - pls review

I have tried out some very basic things; as we try to extend we can update the documentation if there are more things to consdier.

Signed-off-by: Vipin Jain <jainvipin@gmail.com>

2022-12-13 02:48 UTC, glimchb commented on doc/api-extensions.md
> +OPI API objects can be extended by adding `oneof` clause to an existing OPI [grpc proto3 message](https://developers.google.com/protocol-buffers/docs/proto3#any). The example below illustrate the ext
https://developers.google.com/protocol-buffers/docs/proto3#oneof instead of https://developers.google.com/protocol-buffers/docs/proto3#any right, @jainvipin ?

2022-12-13 02:50 UTC, glimchb commented on doc/api-extensions.md
> ++    string new_feature  = 1;
do we enforce same type in the vendor extensions ? can it be string vs int between AMD and Nvidia, for example, on the same `new_feature` ?

2022-12-13 02:54 UTC, glimchb requested changes
It's an excellent start, few minor nits inside the comments

and one question: another common use case is vendors create their own middle end services, probably... how that would look like ?

2022-12-13 08:40 UTC, mkalderon commented on doc/api-extensions.md
> +A generic feature should be considered as part of the native OPI API in the respective areas (network, storage, storage, etc.).
storage appears twice in brackets

2022-12-13 08:40 UTC, mkalderon commented on doc/api-extensions.md
> +a vendor or generically with a vendor
Vipin, can you give an example of limitation vs. modifying generic api to optional ?

2022-12-13 08:40 UTC, mkalderon commented on doc/api-extensions.md
> ++
perhaps we need some way of returning which vendor_extension is valid with some query ?

2022-12-13 08:40 UTC, mkalderon commented on doc/api-extensions.md
> +
not sure I follow this example. How would these messages be used by client/server ?

2022-12-13 18:14 UTC, jainvipin commented on doc/api-extensions.md
> +OPI API objects can be extended by adding `oneof` clause to an existing OPI [grpc proto3 message](https://developers.google.com/protocol-buffers/docs/proto3#any). The example below illustrate the ext
yes the ref needs to be fixed. thanks for the catch!

2022-12-13 18:15 UTC, jainvipin commented on doc/api-extensions.md
> ++    string new_feature  = 1;
we shouldn't in fact likely they are not going to be the same feature, I used the term `new_feature` to illustrate but those features may mean anything to the vendor. If it is the same feature we should bump it up in the OPI APIs.

2022-12-13 18:15 UTC, jainvipin commented on doc/api-extensions.md
> +A generic feature should be considered as part of the native OPI API in the respective areas (network, storage, storage, etc.).
should have been security, thanks for the catch!

2022-12-13 18:42 UTC, jainvipin commented on doc/api-extensions.md
> +a vendor or generically with a vendor
sure the difference is subtle. I can add following in the document for illustration:
```
For example, exposing a limitation on the number of VFs a device should expose, is a limitation
of a device. But all xPUs  limit the maximum number of VFs supported. So this limit may qualify
as a generic limitation and doesn't belong in vendor specific extensions. On the other hand, if a
vendor's product (say, an older generation of xPU) has a limitation on supporting VirtIO device 
emulation on the PF/VFs
```

Similarly features can be put in the similar category
```
For example, providing deeper IO telemetry (e.g. IO completion time, read/write failure codes)
seems generic enough, but can start as a vendor extension (in Status part of an object), and can
make into OPI API as it gains more adoption/support. On the other hand, supporting a custom
programmable compression algorithm is likely goin to be vendor specific feature.
```

The boundaries are blur, and there are some easy ones to fall on either side (generic vs. vendor specific). The ones in the middle ground can start as vendor specific extensions making their way into OPI APIs over time.

2022-12-13 18:43 UTC, jainvipin commented on doc/api-extensions.md
> ++
I feel capabilities discussion is in general needed for OPI - assuming we are going to have optional features. Having said that backend can easily check if vendor specific option is present using `Is...` generated APIs.

2022-12-13 18:44 UTC, jainvipin commented on doc/api-extensions.md
> +
I didn't include the client/server example, because they'd look like filling in any standard grpc message in the generated code.

2022-12-13 19:23 UTC, glimchb commented on doc/api-extensions.md
> ++    string new_feature  = 1;
can you please change the example to use different types and different names just to illustrate that ?

2022-12-13 19:25 UTC, glimchb commented on doc/api-extensions.md
> +a vendor or generically with a vendor
I like this explanation

2022-12-14 20:12 UTC, benlwalker requested changes

2022-12-14 20:12 UTC, benlwalker commented on doc/api-extensions.md
> +allows the discussion on the use cases and if they prove to be generic, and include them natively in the OPI APIs.
I ran this requirement by some large potential consumers of OPI APIs that will have vendor-specific extensions and this requirement is a non-starter. They have extensions that they do not want to make public (and really are specific to them). I've been informed that if this is a requirement of OPI, they'll just skip OPI.

2022-12-14 20:12 UTC, benlwalker commented on doc/api-extensions.md
> ++    oneof vendor_extensions {
What if the extensions are different for every product?

2022-12-14 22:22 UTC, jainvipin commented on doc/api-extensions.md
> ++    oneof vendor_extensions {
they are expected to be, I have modified the examples to illustrate that.

2022-12-14 22:22 UTC, jainvipin commented on doc/api-extensions.md
> +allows the discussion on the use cases and if they prove to be generic, and include them natively in the OPI APIs.
well, one can encode binary blobs using, I have changed the language to 'encouraged' vs mandatory. Please review if that would work for you.
@glimchb - pls also review this updated section

2022-12-14 22:22 UTC, jainvipin commented on doc/api-extensions.md
> +a vendor or generically with a vendor
added

2022-12-14 22:23 UTC, jainvipin commented on doc/api-extensions.md
> +A generic feature should be considered as part of the native OPI API in the respective areas (network, storage, storage, etc.).
fixed

2022-12-14 22:23 UTC, jainvipin commented on doc/api-extensions.md
> ++    string new_feature  = 1;
fixed

2022-12-14 22:23 UTC, jainvipin commented on doc/api-extensions.md
> +OPI API objects can be extended by adding `oneof` clause to an existing OPI [grpc proto3 message](https://developers.google.com/protocol-buffers/docs/proto3#any). The example below illustrate the ext
fixed

2022-12-14 22:36 UTC, glimchb approved these changes
I'm ok with this version

2022-12-14 22:57 UTC, glimchb commented on doc/api-extensions.md
> +allows the discussion on the use cases and if they prove to be generic, and include them natively in the OPI APIs.
looks good

2022-12-14 23:12 UTC, benlwalker commented on doc/api-extensions.md
> +allows the discussion on the use cases and if they prove to be generic, and include them natively in the OPI APIs.
What exactly does supporting a blob extension look like? Is there an any inside every oneof?

2022-12-14 23:13 UTC, benlwalker commented on doc/api-extensions.md
> ++    oneof vendor_extensions {
What is the extension is for a user rather than a particular product or vendor? Remember, on most of these products the customer can load their own software.

2022-12-15 03:15 UTC, pathreya commented on doc/api-extensions.md
> +- The vendor speific messages are kept in the vendor specific directories, however in the above example, they are kept in the same
specific

2022-12-15 03:15 UTC, pathreya commented on doc/api-extensions.md
> ++                               VendorExtensions: &pb.NVMeSubsystemSpec_Amd{&pb.NVMeSubsystemSpecAMD{NewAmdFeature: "foo"}},
It bothers me that the identifiers used here dont match the example above. As in NVMeSubsystemSpec_Amd and NewAmdFeature are not in the example above. Is this as intended?

2022-12-15 16:38 UTC, jainvipin commented on doc/api-extensions.md
> +allows the discussion on the use cases and if they prove to be generic, and include them natively in the OPI APIs.
ok so you'd defined a new message or a field as defined in this document that will have a field `bytes[] hidden_feature1` instead of `string new_feature` in the above example - then contents of that field can be serialized and stored and deserialized and restored from the opaque field.

2022-12-15 16:42 UTC, benlwalker commented on doc/api-extensions.md
> ++    oneof vendor_extensions {
But what if they can't wait until OPI adds it and does a release? What I'm getting at is this strategy doesn't work for the users of OPI, and those potential users have made that clear. What does work is a single any field called 'vendor_extension'.

2022-12-15 16:44 UTC, jainvipin commented on doc/api-extensions.md
> ++                               VendorExtensions: &pb.NVMeSubsystemSpec_Amd{&pb.NVMeSubsystemSpecAMD{NewAmdFeature: "foo"}},
that's due to how code is generated, generated code is camel cased from NVMeSubsystemSpec defined in the proto definitions. The important part is that what client/frontend.go use is same as server/frontend.go. I have tried this out in spdk-bridge code to confirm.

2022-12-15 16:44 UTC, jainvipin commented on doc/api-extensions.md
> +- The vendor speific messages are kept in the vendor specific directories, however in the above example, they are kept in the same
fixed. thanks

2022-12-15 16:44 UTC, jainvipin commented on doc/api-extensions.md
> +gains more adoption/support. On the other hand, supporting a custom programmable compression algorithm is likely goin to be
fixed. thanks

2022-12-15 16:44 UTC, jainvipin commented on doc/api-extensions.md
> +supporting VirtIO device emulation onf PF/VFs, then that would be a vendor (specifically vendor's product) specific limitation.
fixed. thanks

2022-12-15 21:53 UTC, seroyer commented on doc/api-extensions.md
> +supporting VirtIO device emulation on PF/VFs, then that would be a vendor (specifically vendor's product) specific limitation.
This example to me feels more like it should be a capabilities exchange based thing, than a vendor specific extension.  But maybe I'm misunderstanding the example?

2022-12-15 21:53 UTC, seroyer commented on doc/api-extensions.md
> +- Vendor specific messages are enumerated from the values `1024` onwards
Why `1024`?  Is this a "640K ought to be enough for anybody" kind of situation?  Should a cap on the max value be placed to leave room for another range of values to be added later?

2022-12-16 04:49 UTC, jainvipin commented on doc/api-extensions.md
> +- Vendor specific messages are enumerated from the values `1024` onwards
@seroyer - I picked some high number to avoid any conflcit with the field values being added for OPI fields themselves. But this doesn't mean that if we want to go beyond OPI fields can't be added beyond 1024 in a message, it is just that they would not be contiguous (just the optics part of it).

2022-12-16 05:03 UTC, jainvipin commented on doc/api-extensions.md
> +supporting VirtIO device emulation on PF/VFs, then that would be a vendor (specifically vendor's product) specific limitation.
To me, limitations and capabilities are the same thing i.e. not having a capability is a limitation. Capabilities (or limitations) could be generic and or they could be vendor specific capabilities (or limitations). I was thinking that this example is really a vendor specific capability and not a generic capability. Maybe the example is not capturing the vendor specific capability as crisply. How about this example: say a vendor has a limitation (i.e. not have a capability) to do encryption only once at line rate - on both inner IP packet (before tunneling) and outer IP packet (post tunneling). So in order to avoid this, it ma expose this limitation by asking user whether to encrypt inner IP header or outer IP header when implementing IP layer encryption. Of course use can choose to do encryption at both layers, but then it wouldn't be giving them the line rate performance. So exposing an extension to the user to overcome this limitation may be vendor specific.

2022-12-16 13:04 UTC, glimchb commented
PR has enough comments already and I think good start to merge at this point
Every comments from everybody are noted, please feel free to create a new PR so we can have iterative development going here
To scale we need other people start proposing pull requests as well

2022-12-16 13:04 UTC, merged

2022-12-16 14:22 UTC, seroyer commented on doc/api-extensions.md
> +supporting VirtIO device emulation on PF/VFs, then that would be a vendor (specifically vendor's product) specific limitation.
This new example makes more sense for me, thanks.

2022-12-16 14:22 UTC, seroyer commented on doc/api-extensions.md
> +- Vendor specific messages are enumerated from the values `1024` onwards
I guess I'm suggesting we explicitly document the vendor extension range.  For example 1024-2047 and 2048+ are reserved for future use or something.

2022-12-16 18:38 UTC, jainvipin commented on doc/api-extensions.md
> +- Vendor specific messages are enumerated from the values `1024` onwards
makes sense @seroyer - there is a way to do that natively in proto definitions. may be you and I can submit a PR for that separately. Pls let me know.

2022-12-16 18:40 UTC, jainvipin commented on doc/api-extensions.md
> +supporting VirtIO device emulation on PF/VFs, then that would be a vendor (specifically vendor's product) specific limitation.
I will include that in updated text in subsequent PR; thanks you @seroyer for your input!