first revision - cloud protos
opiproject/opi-api pull request #234
Opened 2023-01-18 09:19 UTC by jainvipin

- all protos are verified to compile and autogenerate files
- avoiding autogeneration to reduce clutter and easier review
- haven't defined the RPC messages, will do once proto feedback is incorporated
- tried to split the code between opnnetcommon (something that may be useful elsewhere) from cloud apis
- added documentation for the cloud protos to help understand the object model

ping @glimchb @sandersms @pathreya @mestery

2023-01-18 11:09 UTC, glimchb reviewed
lgtm. good first revision

2023-01-18 21:36 UTC, sandersms approved these changes
Looks good.
The combination of the Readme and the device.proto comments clearly define the layered approach related to the cloud protos.  The device to interface to higher levels flowing up is clear.

2023-01-19 00:55 UTC, timmichels requested changes
My comment about representations captured herein being too specific to a single xPU architecutre is my largest concern.  Many of the elements herein are fine, but some perhaps are not generalized enough and assume a specific underlying match/action HW pipeline.

2023-01-19 00:55 UTC, timmichels commented on network/cloud/v1alpha1/device.proto
> +//
Why all the commented out rpc calls?

2023-01-19 00:55 UTC, timmichels commented on network/cloud/v1alpha1/interface.proto
> +}
Where is the inband control interface terminated on the host - the hypervisor, the VNIC, somewhere else?

2023-01-19 00:55 UTC, timmichels commented on network/cloud/v1alpha1/interface.proto
> +}
In Interface types, how is Uplink_PC different than just Uplink?

2023-01-19 00:55 UTC, timmichels commented on network/cloud/v1alpha1/networkpolicy.proto
> +
The Network Policy API below to me hints at an underlying HW implementation and architecture in its representations and format.  My concern is that it will only map to the xPU it was originally created for.  Do other xPU vendors believe they can consume this API?

2023-01-19 04:59 UTC, jainvipin commented on network/cloud/README.md
> +maps its traffic into a relevant VPC. Of course, the
yes a line got deleted; fixed.

2023-01-19 05:04 UTC, jainvipin commented on network/cloud/v1alpha1/networkpolicy.proto
> +// PolicyRuleFormat captures what format is used for the rules in a given
RuleFormat (flattened vs. compact vs. none) - actually makes the policy implementation independent. It allows xPUs that have flat flow table to work as flattened rules, whereas richer implementations can implement aggregate rules in the datapath pipeline (e.g. programmable P4 pipeline can handle ranges, lists in the datapath), and the caller can take advantage of it. IF you still think otherwise, I will remove RuleFormat field.

2023-01-19 05:08 UTC, jainvipin commented on network/cloud/v1alpha1/subnet.proto
> +  network.opinetcommon.v1alpha1.Encap fabric_encap = 15;
fabric encap is a multiplexed way to specifying encapsulation type (mpls, nvgre, vxlan, etc.) and encap value (e.g. VNI, mpls-label, etc.). So by having an encap for a subnet allows a VNI to be assigned directly to a subnet (as per the comment). Happy to expand more in the comment of this field.

2023-01-19 05:08 UTC, jainvipin commented on network/cloud/README.md
> +
yes, first one is to specify what it logically represents, second one specifies how it gets used in the pipeline for VPC identification.

2023-01-19 05:10 UTC, jainvipin commented on network/cloud/v1alpha1/device.proto
> +//
But after a discussion if we need one service with all APIs or different grpc services. Any opinons? I'd prefer one grpc service, but wasn't sure what others would prefer.I could take ti up in this PR, or another PR.

2023-01-19 05:16 UTC, jainvipin commented on network/cloud/v1alpha1/interface.proto
> +}
Uplink PC is a port-channel i.e. multiple ports can form a 802.3ad link aggregation port (kinda like NIC bonding on linux) towards the Top of rack from the xPU's ports.

2023-01-19 05:21 UTC, jainvipin commented on network/cloud/v1alpha1/networkpolicy.proto
> +
Let's discuss - would love opinion from others.
The structure of policy is very generic SecurityPolicy has a bunch of ordered Rules, each rule has priority(order), matching criteria (5 tuple in various forms), and action (permit/deny). Besides it can be applied in ingress or egress direciton at various attachment points (subnet, vpc, etc.). Do you think, it would help if this hierarchy of network security policy is documented?

2023-01-19 06:09 UTC, pathreya requested changes

2023-01-19 06:09 UTC, pathreya commented on network/cloud/v1alpha1/device.proto
> +  int32 pcie_port_count = 6;
What is pcie_port logically? Is it different than the pf that the host sees?

2023-01-19 06:09 UTC, pathreya commented on network/cloud/v1alpha1/device.proto
> +message DeviceStatus {
Is this message represents something the device natively advertises(like info and caps) OR is it the status after a configuration? If its latter, i think a structure is needed for capabilities and immutable device information which can be separate from the status fields which are dynamic based on configuration or state of the device.

2023-01-19 06:09 UTC, pathreya commented on network/cloud/v1alpha1/device.proto
> +  bool overlay_routing_enabled = 7;
I think it affects the pipeline? Perhaps not a global device config then.

2023-01-19 06:09 UTC, pathreya commented on network/cloud/v1alpha1/device.proto
> +  network.opinetcommon.v1alpha1.IPAddress gateway_ip = 5;
Is this(and ipvX_address) best addressed by API Spec OR is it better configured by the lifecycle management?
@glimchb thoughts?

2023-01-19 11:56 UTC, glimchb commented on network/cloud/v1alpha1/device.proto
> +//
I favor the approach to comment out RPC's in this PR and focus on messages and if all agree, do the RPC pull request separately following this one...

2023-01-19 12:01 UTC, glimchb commented on network/cloud/v1alpha1/device.proto
> +message CreateDeviceRequest {
- from Controller to xPU
- Yes, lifecycle management group can investigate how to advertise management end points so Controllers can find xPUs. It could be static config or it could be dynamic advertisement... ssdp... dhcp... mdns... slaac... In any case should be out of scope for this PR

2023-01-19 12:03 UTC, glimchb commented on network/cloud/v1alpha1/device.proto
> +message PCIeFunctionsSpec {
we can potentially use `PciEndpoint` from https://github.com/opiproject/opi-api/blob/main/storage/v1alpha1/opicommon.proto#L22

2023-01-19 18:01 UTC, pathreya commented on network/cloud/v1alpha1/networkpolicy.proto
> +// Copyright (c) 2023 Pensando, AMD Inc, or its subsidiaries.
I think we can avoid NetworkPolicy for now. I wont be reviewing it in this PR.

2023-01-19 18:05 UTC, pathreya commented on network/cloud/v1alpha1/port.proto
> +  PortXcvrStatus             xcvr_status = 3;
I'd like xcvr_status, fsm_xxx to be optional.

2023-01-19 18:05 UTC, pathreya commented on network/cloud/v1alpha1/port.proto
> +  int32                      mac_ch      = 6;
Can you clarify what is mac channel?

2023-01-19 18:09 UTC, pathreya commented on network/cloud/v1alpha1/cproute.proto
> +// protobuf specification for Control Plane (i.e. underlay) Route Table
I think CP is a misnomer since this route table is consulted for datapath of all traffic(tenant or xPU). Perhaps ulroute is more apt.

2023-01-19 18:11 UTC, pathreya commented on network/cloud/v1alpha1/vnic.proto
> +  // identifier of ingress IPv4 security policy to be enforced
fields related to policy need to be optional.

2023-01-19 18:12 UTC, pathreya commented on network/cloud/v1alpha1/vnic.proto
> +  bool allow_internet_access   = 28;
I think this setting belongs under network policy

2023-01-19 18:12 UTC, pathreya commented on network/cloud/v1alpha1/vnic.proto
> +  int32 max_cps = 29;
CPS settings belong under network policy.

2023-01-19 18:13 UTC, pathreya commented on network/cloud/v1alpha1/vnic.proto
> +  int32 max_tcp_sessions = 38;
max_xxx belong under policy

2023-01-19 23:16 UTC, jainvipin commented on network/cloud/README.md
> +
First thing to be done for egress traffic is always tenant/vpc identification; usually cloud provider wouldn't trust the IP address (from a mapping object) to identify the workload. The trusted way to identify the workload is to use its VNIC. Once the VPC is identified, it tells various attributes of the VPC to help route the traffic (besides other things). Mapping object at this stage can be used to to source-guard checks i.e. ensure that sender is not spoofing the src-ip/mac. Later mapping object is used to do the routing lookup because mapping is also a /32 or /128 route. identifying the destination host.

2023-01-19 23:17 UTC, jainvipin commented on network/cloud/v1alpha1/device.proto
> +//
ack @glimchb - incremental progress is better, to avoid discussion diluation.

2023-01-19 23:20 UTC, jainvipin commented on network/cloud/v1alpha1/device.proto
> +// PCIe functions to be configured on the device
yes the VFs/PFs would be visible on the host. For virtualization, these VFs can be mapped into VMs (with hypervisor bypass), or inside a K8s pod. OTOH, if it is a bare-metal workload these PFs/VFs are used by the tenant. e.g. bring your own hypervisor is a good use case for scheduling BM resources in public cloud.

2023-01-19 23:51 UTC, jainvipin commented on network/cloud/v1alpha1/device.proto
> +message CreateDeviceRequest {
@glimchb is correct; all GRPC APIs are from controller to xPU. xPU is managed northbound by cloud infra controller. We need to tee off from lifecycle APIs to be handed over to network SDN control plane to start managing the datapath. Clearly no tenant workoads can be provisioned while all this is being bootstrapped.

I have updated README.md with a section describing the management path and OS boot dependencies.

2023-01-19 23:52 UTC, jainvipin commented on network/cloud/v1alpha1/device.proto
> +  int32 pcie_port_count = 6;
no it is number of PFs a cloud provider seeks to be exposed from this device.

2023-01-20 00:03 UTC, jainvipin commented on network/cloud/v1alpha1/device.proto
> +message DeviceStatus {
good point - I wasn't sure if capabilities belonged to network APIs, but I think we can put network capabilities in network APIs. Given that,  I have added another API to fetch the device capabilities. I have added a few candidate fields in there, but feel free to submit a PR to add more capabilities there. Pls see `DeviceCapabilities` in the updated PR. Also note @timmichels, this would also address the concern about flattened vs. compact rules comment you made earlier.

2023-01-20 00:11 UTC, jainvipin commented on network/cloud/v1alpha1/vnic.proto
> +  int32 max_cps = 29;
this is not underlay configuration - this is a limitation put on to a tenant's workload (via VNIC object) by the cloud provider to help manage the connection/sec resources fairly among various tenants.

2023-01-20 00:15 UTC, jainvipin commented on network/cloud/v1alpha1/vnic.proto
> +  int32 max_tcp_sessions = 38;
Well the thought was that network security policy would defined permit/deny rules based on the 5-tuple, and also network security policy is defined by the customer to restrict who can talk to who in tenant network. However even if a VNIC/VPC/Subnet is not configured with any security policy a cloud infra may want to limit the max# sessions based on the workload profile (e.g. an instance that is higher #CPUs may be allowed more sessions vs. a tiny instance may be restricted).

2023-01-20 00:17 UTC, jainvipin commented on network/cloud/v1alpha1/vnic.proto
> +  // identifier of ingress IPv4 security policy to be enforced
yes we haven't annotated any of the fiels as mandatory vs. optional. But clearly security policy on VNIC is optional and is usually triggered by the tenant's intent.

2023-01-20 00:20 UTC, jainvipin commented on network/cloud/v1alpha1/vnic.proto
> +  bool allow_internet_access   = 28;
Permitting internet access is typically a workload instance (e.g. VM instance) attribute. Having said that yes this is a policy but for a workload (i.e. a VNIC). If we move this to network security policy we'd have to define the behavior for other entities that can also be attaching network security policy.
Let's hear from others about how to define workload specific attributes in a generic network policy structure. Or, would it help if we take all the policy specific fields in VNIC in a separate message and refer to them here, instead of calling out the fields natively?

2023-01-20 00:21 UTC, jainvipin commented on network/cloud/v1alpha1/port.proto
> +  PortXcvrStatus             xcvr_status = 3;
ack

2023-01-20 00:22 UTC, jainvipin commented on network/cloud/v1alpha1/networkpolicy.proto
> +// Copyright (c) 2023 Pensando, AMD Inc, or its subsidiaries.
ok - let's hear from others. I can take it out. However this was targeted to be kept in the first rev. @glimchb @sandersms ?

2023-01-20 00:23 UTC, jainvipin commented on network/cloud/v1alpha1/bgp.proto
> +// Copyright (c) 2023 Pensando, AMD Inc, or its subsidiaries.
ack - pls check the capability message. I can also remove the bgp.proto in this PR and come to it later if there is a consensus on moving it out for now.

2023-01-20 00:24 UTC, jainvipin commented on network/cloud/v1alpha1/cproute.proto
> +// protobuf specification for Control Plane (i.e. underlay) Route Table
sure - let's find a better name. I'd prefer `UnderlayRoute` in that case. If others want to opine, this would be a good time.

2023-01-20 00:31 UTC, jainvipin commented on network/cloud/v1alpha1/device.proto
> +  bool overlay_routing_enabled = 7;
It affects the pipeline but it is a networking configuration so we need to define it at some place. If this field set then overlay traffic is routed, otherwise it is bridged i.e. forwarded within the subnet only based on the MAC address. Can be useful for EVPN use case that someone brought up. If using bridging (e.g. EVPN) it make sense to do it for all VPCs i.e. globally and not selectively, otherwise it can get confusing.

2023-01-20 00:33 UTC, jainvipin commented on network/cloud/v1alpha1/device.proto
> +  network.opinetcommon.v1alpha1.IPAddress gateway_ip = 5;
IMO, lifecycle should be only relying upon and using management interface's connection. This is the gateway IP configuration for the underlay.

2023-01-20 00:35 UTC, jainvipin commented on network/cloud/v1alpha1/device.proto
> +message PCIeFunctionsSpec {
may be I named it poorly - this message is really specifying how many pcie functions to expose, to the host. Where as https://github.com/opiproject/opi-api/blob/main/storage/v1alpha1/opicommon.proto#L22  indicates the actual details the the PCIe endpoint which definitely belongs in there for storage related VFs.

2023-01-20 00:47 UTC, jainvipin commented on network/cloud/v1alpha1/cproute.proto
> +  uint32 admin_dist = 7;
This configuration has is not the metric in linux kernel routes. For static routes (vs dynamic where distance is computed by protocol), this is the configured admin-distance set by the controller for this route to help find the best next hop in RIB. This control can be used by the static routing to configure specific paths (via distance) for underlay routes.

2023-01-20 00:47 UTC, jainvipin commented on network/cloud/v1alpha1/cproute.proto
> +  uint32 admin_dist = 7;
I have updated the comment for this field in the PR.

2023-01-20 00:51 UTC, jainvipin commented on network/cloud/v1alpha1/cproute.proto
> +  bool override = 6;
not really, this can be used to override admin distance of a route that is computed equidistant in the default calcuation. Since 'zero' is a valid admin_distance, this bool really idenfies if admin_dist is valid or not.

2023-01-20 00:55 UTC, jainvipin commented on network/cloud/v1alpha1/device.proto
> +  network.opinetcommon.v1alpha1.IPAddress gateway_ip = 5;
On second thought, this was called control plane route, because this is a static substitution to what a routing protocol (aka control plane) would have computed, and so control plane route. Either way - I am okay, just providing the context for everyone.

2023-01-23 12:18 UTC, chaudron commented
I like the README.md as it explains the use case and bits of the pipeline. 

As mentioned earlier, what I think we should use, are the OpenConfig definitions as they are already in use for a while, and major routing vendors are using them. If we do miss items in the definitions we could add them.

During the January 19th meeting, someone brought up that we need some form of capability checking. Briefly looking at the gNMI protocol and clients, this seems to be built in (https://github.com/akarneliuk/pygnmi, https://www.openconfig.net/docs/gnmi/gnmi-specification/#32-capability-discovery).

I know someone was looking at providing an example client/server, but this might be delayed due to the Chinese New Year.

So my take would be, rather than trying to push our own Protobuf definitions, try to use OpenConfig + gNMI and add any missing mandatory attributes.

Briefly looking at the general interface (.proto), most of the fields are there. If found this page explaining a bit about how OpenConfig definitions should be converted to protocol buff, https://www.openconfig.net/docs/gnmi/protobuf-vals/

//Eelco

2023-01-23 17:47 UTC, jainvipin commented
> I like the README.md as it explains the use case and bits of the pipeline.
> 
> As mentioned earlier, what I think we should use, are the OpenConfig definitions as they are already in use for a while, and major routing vendors are using them. If we do miss items in the definitions we could add them.
> 
> During the January 19th meeting, someone brought up that we need some form of capability checking. Briefly looking at the gNMI protocol and clients, this seems to be built in (https://github.com/akarneliuk/pygnmi, https://www.openconfig.net/docs/gnmi/gnmi-specification/#32-capability-discovery).
> 
> I know someone was looking at providing an example client/server, but this might be delayed due to the Chinese New Year.
> 
> So my take would be, rather than trying to push our own Protobuf definitions, try to use OpenConfig + gNMI and add any missing mandatory attributes.
> 
> Briefly looking at the general interface (.proto), most of the fields are there. If found this page explaining a bit about how OpenConfig definitions should be converted to protocol buff, https://www.openconfig.net/docs/gnmi/protobuf-vals/
> 
> //Eelco
thanks @chaudron - I will let others also opine on this. 

I am not a savvy openconfig user (esp when it comes to proto generation) so for me, I wouldn't mind (or it will help) if someone can submit a PR for these definitions in Openconfig that can generate these proto definitions. OTOH, assuming we can generate similar kind of proto definitions out of openconfig YANG model, we can start working on the backend reference implementation around these APIs to make progress.

2023-01-24 07:34 UTC, chaudron commented
> thanks @chaudron - I will let others also opine on this.
> 
> I am not a savvy openconfig user (esp when it comes to proto generation) so for me, I wouldn't mind (or it will help) if someone can submit a PR for these definitions in Openconfig that can generate these proto definitions. OTOH, assuming we can generate similar kind of proto definitions out of openconfig YANG model, we can start working on the backend reference implementation around these APIs to make progress.

The same for me, however, we had an internal discussion around the subject of OpenConfig/IETF and we are trying to get some "experts" involved. Give us a couple of days.

2023-01-26 20:21 UTC, jainvipin commented on network/cloud/v1alpha1/cproute.proto
> +  // The number of seconds since this route was last updated or otherwise determined to be correct.
@pathreya - as for making these fields optional, certainly we can add google options to be tagged to these fields.
@glimchb - WDYT? should I include grpc `optional` attributes to various fields in this PR? I can do a sweep at all the fields and do it. There are a large # of fields optional in this API, not just the one @pathreya points out.

2023-01-26 20:29 UTC, jainvipin commented on network/cloud/v1alpha1/cproute.proto
> +  int32 metric1 = 9;
fixed

2023-01-26 20:33 UTC, jainvipin commented on network/cloud/v1alpha1/cproute.proto
> +  // The number of seconds since this route was last updated or otherwise determined to be correct.
rest of the comments incorporated @pathreya - pls review.

2023-01-31 18:13 UTC, pathreya approved these changes
Based on offline exchange, I will submit PR for fields that will need to be optional for Marvell to be compliant with this spec. Optional fields will be identified in the API using https://linter.aip.dev/203/optional.
Hence this PR is approved from my end.

2023-01-31 20:02 UTC, glimchb commented
@timmichels do you still have an objection or we can merge this ?

2023-02-02 18:29 UTC, glimchb commented
good first proposal, we can iterate on top of this. merging

2023-02-02 18:29 UTC, merged