EVPN Gateway API
opiproject/opi-api pull request #276
Opened 2023-04-18 09:37 UTC by mardim91

EVPN Gateway API for provisioning integrated L2 and L3 network instances on an xPU

2023-04-18 11:41 UTC, glimchb requested changes
Thank you for the contribution.
I’m not commenting on content yet.
From style perspective put several comments inside. We are compliant with AIP. When you run make, the linters will fail. Please check the comments and run linters to verify.

2023-04-18 11:41 UTC, glimchb commented on network/evpn-gw/l2_ipu_infra_mgr.proto
> +    rpc DeleteLB(LogicalBridgeId) returns (DeleteLBResult);
Empty result is expected from delete https://google.aip.dev/135

2023-04-18 11:41 UTC, glimchb commented on network/evpn-gw/l2_ipu_infra_mgr.proto
> +    repeated LogicalBridgeInfo logical_bridges = 1;
The repeated name is not consistent with message name

2023-04-18 11:41 UTC, glimchb commented on network/evpn-gw/l2_ipu_infra_mgr.proto
> +    rpc CreateLB(LogicalBridgeInfo) returns (CreateLBResult);
The object itself and not result is expected from create method see https://google.aip.dev/133

2023-04-18 11:41 UTC, glimchb commented on network/evpn-gw/l2_ipu_infra_mgr.proto
> +    rpc GetLB(LogicalBridgeId) returns (GetLBResult);
The object itself and not result is expected from get method see https://google.aip.dev/131

2023-04-18 11:41 UTC, glimchb commented on network/evpn-gw/l2_ipu_infra_mgr.proto
> + * ============LICENSE_START=======================================================
We use short spdx license style one liner

2023-04-18 11:41 UTC, glimchb commented on network/evpn-gw/images/data-model-evpn-gw-api.png
You can use github mermaid to create a diagram inside markdown

2023-04-18 11:41 UTC, glimchb commented on network/evpn-gw/README.md
> +<p align="center">
Embedded htlm is not allowed. You can insert and image in md style.

2023-04-18 15:06 UTC, glimchb commented on network/evpn-gw/l2_ipu_infra_mgr.proto
> +/*-
IPU is not appropriate in the name for the proto file

2023-04-18 15:46 UTC, dandaly commented on network/evpn-gw/l2_ipu_infra_mgr.proto
> +/*-
I agree with this comment, I would ask that we hold all of the checkins to the same threshold where a single DPU or IPU is not correct.  It should be applied evenly across.

2023-04-18 17:00 UTC, jainvipin requested changes
Cloud APIs as it is defined today, allows a multi-tenant BGP Based route/mac distribution and define following objects:
- SVI object, defined as subnet object
- VRF object, defined as VPC object
- BP object, defined as VNIC (and port) objec that can belong to a subnet/VPC
- Finally logical bridge is no different from subnet object if l3 routing is not enabled
Furthermore BGP object defines peering with the adjacent router (or RR) to distribute BGP routes via EVPN (type2, type3) routes.

Having said that I am not sure excactly how this alings with K8s work happening in parallel.

2023-04-18 18:36 UTC, glimchb commented
> Cloud APIs as it is defined today, allows a multi-tenant BGP Based route/mac distribution and define following objects:

@jainvipin maybe if you can add link to the proto file, it would be helpful

2023-04-18 18:47 UTC, glimchb commented
maybe this kinda picture @jainvipin had in mind that Intel and Ericsson presented in their demo:
![image](https://user-images.githubusercontent.com/36732377/232874166-18fabf3a-ba83-4398-a68e-46a8ba378996.png)

2023-04-18 21:03 UTC, jainvipin commented
> maybe this kinda picture @jainvipin had in mind that Intel and Ericsson presented in their demo: ![image](https://user-images.githubusercontent.com/36732377/232874166-18fabf3a-ba83-4398-a68e-46a8ba378996.png)

this pic is very helpful in understanding the implementation, we should add this in the PR. I went over the demo recording for this and there was also a use case slide that is worth included for anyone wanting to get more context on this use case.

2023-04-18 22:12 UTC, jainvipin commented
> > Cloud APIs as it is defined today, allows a multi-tenant BGP Based route/mac distribution and define following objects:
> 
> @jainvipin maybe if you can add link to the proto file, it would be helpful

VPC (aka vrf object): https://github.com/opiproject/opi-api/blob/main/network/cloud/v1alpha1/vpc.proto
Subnet (aka SVI/LogicalBridge object): https://github.com/opiproject/opi-api/blob/main/network/cloud/v1alpha1/subnet.proto
Tunnel (for encapsulating packets): https://github.com/opiproject/opi-api/blob/main/network/cloud/v1alpha1/tunnel.proto
Port (Bridge Port object): can be https://github.com/opiproject/opi-api/blob/main/network/cloud/v1alpha1/vnic.proto (can add vlan-id in addition to vni here)

Cloud objects do have a whole bunch of other things that are perhaps not needed in this PR. So we can make a call if we want to keep it separate for now and look at common elements later, or do it now.

2023-04-20 09:12 UTC, mardim91 commented
> > Cloud objects do have a whole bunch of other things that are perhaps not needed in this PR. So we can make a call if we want to keep it separate for now and look at common elements later, or do it now.
> 
> My opinion - we need to at least try to find common objects now and split instead of duplicating. It could be shared folder between cloud and eVPN GW or just a cloud folder... I'm ok with either approach.
> 
> @mardim91 can you please look at @jainvipin links and see if those can fit your needs instead of defining a new ones... ?

Hello @glimchb and @jainvipin it will take some time to review the cloud API and find common ground (if any) with our EVPN GW API. Is there any recording or slideck that the cloud API has been presented so we can get more context on how this API is implemented, what is the use case in mind  and how the different obhects are getting created and connected to eachother ?

2023-04-20 16:52 UTC, sandersms commented
A couple of things to consider:
1) Openconfig has definitions for EVPN https://github.com/openconfig/public/blob/master/doc/evpn_use_cases.md
2) The openconfig has models for both EVPN and VRF that are part of the network instance models at: https://github.com/openconfig/public/tree/master/release/models/network-instance

Is it possible to leverage the applicable models to align with existing solutions that exist today for Network configuration operations.

2023-04-27 08:28 UTC, mardim91 commented on network/evpn-gw/l3_xpu_infra_mgr.proto
> +syntax = "proto3";
@glimchb yes I know. The only reason I have putted it there for now is to make the linter run only in the l2_xpu file and not l3_xpu so I do not get overwhelmed from the linting errors. 

Please take a look to the l2_xpu_infra_mgr.proto to check if all is ok with this file at least. Now is free from linitng errors

2023-04-28 09:15 UTC, mardim91 commented
> A couple of things to consider:
> 
> 1. Openconfig has definitions for EVPN https://github.com/openconfig/public/blob/master/doc/evpn_use_cases.md
> 2. The openconfig has models for both EVPN and VRF that are part of the network instance models at: https://github.com/openconfig/public/tree/master/release/models/network-instance
> 
> Is it possible to leverage the applicable models to align with existing solutions that exist today for Network configuration operations.

@sandersms We for sure would like in the future to take a look and study the openconfig part and see if we can align our API with the openconfig standards. For the meanwhile we would like to merge this API as it is and then study openconfig and see if we can align. I hope this is ok with you.

2023-05-01 20:14 UTC, glimchb commented
@mardim91 please note MD linter errors 
https://github.com/opiproject/opi-api/actions/runs/4832277890/jobs/8652033745?pr=276

2023-05-01 20:15 UTC, glimchb commented on network/evpn-gw/README.md
> +```mermaid
excellent!

2023-05-05 04:31 UTC, jainvipin requested changes
thanks @mardim91 for submitting this PR. I have put in some comments here. we should discuss some of them a bit more. There are some small comments but the big ones are:
1. Lack of `Spec` and `Status` is very clearly seen as fields are getting mixed up
2. Opaque keys (aka IDs in various other OPI object definitions) alllows identification and reference to the objects very cleanly. This is not the case here, in some cases field values are used as refrence, in some cases names. Not only this lacks consistency but breaks abstraction. Moving to a consistent key-ids can fix this issue.
3. There definitely seems to be a lot of side-band fixup needed for these APIs to work i.e. we'll need to introduce some more objects, especially route-table (to control linux routing perhaps), BGP (no RR and/or local/bgp-peer configuration), underlay configuration is not there, VNIC (as vport_id is very opaque w.r.t. what user really wants e.g. VF or netdev virtual interface), etc.
4. Finally, underlying implementation being linux (vs. if it is P4) is evident from this API. I was hoping GRPC layer abstracts out the implementation.

2023-05-05 04:31 UTC, jainvipin commented on network/evpn-gw/v1alpha1/l3_xpu_infra_mgr.proto
> +    uint32 routing_table = 3;
Few comments:
1. If this defaults to vNI and VNI can be 24bits as per VXLAN spec, and linux routing table is ranging from 1001-3999 then this would limit my VNI to be total 3k (1k - 4k).
2. Same comment as above - linux abstraction shouldn't come out. e.g. if I were to create grpc APIs that are eeking out P4 implementation then the abstraction is assumed not clean.
3. The routing table is dropping out of no-where, basically it assumes that there is someone else configuring the linux table behind the scenes. A good indication that this API is not complete. Please take a look at route-table object in cloud APIs that is linked to VRF/VPC object there. A similar construct is needed here for it to be wholesome/clean.

2023-05-05 04:31 UTC, jainvipin commented on network/evpn-gw/v1alpha1/l3_xpu_infra_mgr.proto
> +    string vtep_ip = 5;
Should VTEP/Tunnel be a different object - I mean why combine it with VRF object? Can there be multiple VTEPs per VRF?

2023-05-05 04:31 UTC, jainvipin commented on network/evpn-gw/v1alpha1/l3_xpu_infra_mgr.proto
> +    uint32 local_as = 6;
`local_as`, `rd` are BGP attributes - shoudl bgp attributes be separated (and also add remainder of bgp configuration such as local bgp and peer bgp (or RR) configuration. This would allow any controller based EVPN implementation to work with this too where there is no explicit BGP configuration is needed.

2023-05-05 04:31 UTC, jainvipin commented on network/evpn-gw/v1alpha1/l3_xpu_infra_mgr.proto
> +    // Read-only: Router MAC address of the VRF
read only object => `Status`

2023-05-05 04:31 UTC, jainvipin commented on network/evpn-gw/v1alpha1/l3_xpu_infra_mgr.proto
> +    repeated uint32 vlan_ids = 11;
Instead of `LocalBridges`, shouldn't this be a reference to SVI objects instead. I mean VRF is a routing construct, and without SVIs this is meaningless. Where as SVI is truly a routed interface and therefore this should be what we refer here. In that sense, it would be nice to have SVI object referred to using key-ids (like rest of the OPI objects) which then can be referrerd to here.
repeat comment - read only field can be in status.

2023-05-05 04:31 UTC, jainvipin commented on network/evpn-gw/v1alpha1/l3_xpu_infra_mgr.proto
> +    // Use "aa:bb:cc:dd:ee:ff" format. Randomly assigned if not specified
is this the router MAC?

2023-05-10 15:46 UTC, mardim91 commented on network/evpn-gw/v1alpha1/l2_xpu_infra_mgr.proto
> +    uint32 vni = 3;
we are calling it logicalBridge not localbridge. Why are you reffering to a localBridge ?

2023-05-10 15:54 UTC, mardim91 commented on network/evpn-gw/v1alpha1/l2_xpu_infra_mgr.proto
> +    repeated uint32 vlan_id = 5;
The Vlan-id is a key of identyfying uniquely the LogicalBirdges. The array of Vlan_ids here is used for the trunk case where a bridgeport carries more that one VLANs which means belongs to 1 or more logicalBridges

2023-05-11 06:59 UTC, mardim91 commented on network/evpn-gw/v1alpha1/l2_xpu_infra_mgr.proto
> +message LogicalBridge {
The reason that we have called it LogicalBridge is because each LogicalBridge forms a L2Forwarding Domain based on VLANs so we think that the term LogicalBridge is more suitable in this case.

2023-05-11 09:40 UTC, mardim91 commented on network/evpn-gw/v1alpha1/l2_xpu_infra_mgr.proto
> +    uint32 vlan_id = 2 [(google.api.field_behavior) = REQUIRED];
The Vlan id has only local signification. Will not span accross different nodes. This mean that different Vlans in different nodes can belong to the same VNI but because VLAN has Local significance then vlan_id can be used as key.

2023-05-11 09:44 UTC, mardim91 commented on network/evpn-gw/v1alpha1/l2_xpu_infra_mgr.proto
> +        UNKNOWN = 0;
This is a convention from the Protobuf documentation where you have to explicitely list the default value "0"

2023-05-11 09:46 UTC, mardim91 commented on network/evpn-gw/v1alpha1/l2_xpu_infra_mgr.proto
> +    uint32 vport_id = 2;
The vport_id is local concept is not for global identifiaction. We have chosen to do it this way. This is not intented to be used as key for global identification but only for local identification.

2023-05-11 09:54 UTC, mardim91 commented on network/evpn-gw/v1alpha1/l3_xpu_infra_mgr.proto
> +    // Key, also used as name of the Linux vrf device (max 9 chars)
I will remove all the LInux comments from the API.

2023-05-11 10:00 UTC, mardim91 commented on network/evpn-gw/v1alpha1/l3_xpu_infra_mgr.proto
> +    uint32 routing_table = 3;
We can put the routing table that has been configured as Status field. But either way is part of the VRF configuration and we handle that internally on the infra manager. We can remove the binding of the VNI to the route table id. We can assume that all the VNI values are globally unique.

2023-05-11 10:02 UTC, mardim91 commented on network/evpn-gw/v1alpha1/l3_xpu_infra_mgr.proto
> +    string vtep_ip = 5;
Is a reference to an allready existing Tunnel endpoint that is configured on the xPU. This is outside the scope of the current API.

2023-05-11 10:04 UTC, mardim91 commented on network/evpn-gw/v1alpha1/l3_xpu_infra_mgr.proto
> +    uint32 local_as = 6;
We are not configuring them. We can put them in the Status fields.

2023-05-11 10:07 UTC, mardim91 commented on network/evpn-gw/v1alpha1/l3_xpu_infra_mgr.proto
> +    repeated uint32 vlan_ids = 11;
We can put it in the Status and we can remove the Vlan ids and replace it with SVI Ids.

2023-05-11 12:12 UTC, mardim91 commented
> thanks @mardim91 for submitting this PR. I have put in some comments here. we should discuss some of them a bit more. There are some small comments but the big ones are:
> 
> 1. Lack of `Spec` and `Status` is very clearly seen as fields are getting mixed up
**[Dimitris] We believe this is a really good point to use the Spec and Status concept. I will change the API to reflect that.**
> 2. Opaque keys (aka IDs in various other OPI object definitions) alllows identification and reference to the objects very cleanly. This is not the case here, in some cases field values are used as refrence, in some cases names. Not only this lacks consistency but breaks abstraction. Moving to a consistent key-ids can fix this issue.
**[Dimitris] I agree that using IDs (e.g. UUIDs in Openstack case) as keys to uniquely identify is is more clear than using other fields. The problem with UUIDs is that you need additional checks for the other fields in order to evaluate the uniqness of a field. (e.g. If you use UUIDs as key to LogicalBridges then you need extra functionality to implement in order to be sure that the vlan_id field of a newly created LogicalBridge is also unique as you cannot have two LogicalBridges with the same vlan-id. This is not the case of course if you use vlan-id as key because the vlan-id will represent uniqness of the LogicalBridge.)
Also makes the reference easier if you do not use UUIDs. For instance if you want as a user to say which BirdgePort belongs to which LogicalBridge then you need to find first which is the UUID of the LogicalBridge and use that as parameter during the creation of the BridgePort in order to refernce the LogicalBridge that the BridgePort belongs to which is a bit of a struggle. Overall UUIDs are cleaner and more machine friendly but using non UUIDs keys are more user friendly. We need to have a discussion in the OPI-API meeting to decide which approach we would like to follow on all APIs that are submitted.**
> 3. There definitely seems to be a lot of side-band fixup needed for these APIs to work i.e. we'll need to introduce some more objects, especially route-table (to control linux routing perhaps), BGP (no RR and/or local/bgp-peer configuration), underlay configuration is not there, VNIC (as vport_id is very opaque w.r.t. what user really wants e.g. VF or netdev virtual interface), etc.
**[Dimitris] Currenlty we do not deal with BGP configuration and underlay we take that as already preconfigured objects. We do not have any intetion to include that in the API for now. Also in our PoC we had only VFs and that's why we do not specify something else as type during the BridgePort creation. Maybe in the future we can revisit that.** 
> 4. Finally, underlying implementation being linux (vs. if it is P4) is evident from this API. I was hoping GRPC layer abstracts out the implementation.
**[Dimitris] We can remove any Linux words/statements from the API comments.**

2023-05-18 15:56 UTC, jainvipin commented on network/evpn-gw/v1alpha1/l2_xpu_infra_mgr.proto
> +    uint32 vni = 3;
sorry, logicalBridge is good!

2023-05-24 14:32 UTC, mardim91 commented on network/evpn-gw/README.md
> +We present a lean and tailor-made EVPN Gateway API for provisioning integrated L2 and L3 network instances on an xPU, with the option to connect these to L2- and/or L3-VPN instances through an EVPN G
Picture has been provided with extensive explanation.

2023-05-24 14:35 UTC, mardim91 commented on network/evpn-gw/README.md
> +The EVPN Gateway API in the Kubernetes context is used for network provisioning before and after the cluster instantiation, as well as interface configuration during pod creation.
I believe this has been answered allready in the a previous use case and API working group meeting. Also detailed explanation has been added together with the architecture design image. If more explanation is needed let me know.

2023-05-24 14:41 UTC, mardim91 commented on network/evpn-gw/README.md
> +    A bridge port connects a tenant to one or more Logical Bridges. The model supports both access and trunk ports. An access port receives untagged frames from tenants and maps frames to the configu
I believe everything is explained to the different presentations in the use case and API workgroup meetings and lso in the extensive explanation of the Arch picture that has been added to this README. If you have more questions please let me know

2023-05-24 15:07 UTC, mardim91 commented on network/evpn-gw/v1alpha1/l2_xpu_infra_mgr.proto
> +    // Format: bridge_ports/{bridge_port}
Done

2023-05-26 00:40 UTC, jainvipin reviewed
usually the URLs and references are not case sensitive....making them case sensitive can create incompatibilities. Suggest changing all camelCase nameing to all lowercase naming.

2023-05-26 09:06 UTC, mardim91 commented
> usually the URLs and references are not case sensitive....making them case sensitive can create incompatibilities. Suggest changing all camelCase nameing to all lowercase naming.

I have just tried to follow the google standards. You can see in the image below that the resource reference has been written with a capital letter

![image](https://github.com/opiproject/opi-api/assets/26648396/1da2edc7-b498-4ba4-9ba5-f6e00b6cf3eb)

2023-05-31 05:05 UTC, jainvipin commented
LGTM @mardim91  !!

2023-06-01 16:09 UTC, jainvipin approved these changes
LGTM!

2023-07-13 17:02 UTC, glimchb approved these changes
per API meeting 7/13/2023 approved and merged

2023-07-13 17:03 UTC, merged