Storage: Multipath support
opiproject/opi-api pull request #297
Opened 2023-06-02 19:57 UTC by benlwalker

* Separate the path object from the controller, leaving open the possibility to have multiple paths.
* Discovery namespaces by connecting to controllers

2023-06-02 22:49 UTC, glimchb commented on storage/v1alpha1/backend_nvme_tcp.proto
> +    repeated NVMfRemoteNamespace namespaces = 1;
should be `nv_mf_remote_namespaces`

2023-06-02 22:51 UTC, glimchb reviewed
to fix linters you can apply this patch
```
diff --git a/storage/v1alpha1/backend_nvme_tcp.proto b/storage/v1alpha1/backend_nvme_tcp.proto
index 104da84..1f4b9b7 100755
--- a/storage/v1alpha1/backend_nvme_tcp.proto
+++ b/storage/v1alpha1/backend_nvme_tcp.proto
@@ -213,7 +213,7 @@ message ListNVMfRemoteNamespacesRequest {
 }

 message ListNVMfRemoteNamespacesResponse {
-    repeated NVMfRemoteNamespace namespaces = 1;
+    repeated NVMfRemoteNamespace nv_mf_remote_namespaces = 1;
     string next_page_token = 2;
 }
```

2023-06-02 22:52 UTC, glimchb commented on storage/v1alpha1/backend_nvme_tcp.proto
> +    common.v1.ObjectKey id = 1;
this should be:
```
    // user can only set {resource}_id on the Create request object
    string name = 1;
```

2023-06-06 14:43 UTC, artek-koltun commented on storage/v1alpha1/backend_nvme_tcp.proto
> +    int32 nsid = 4;
int32 nsid = 4;
and subsequent

2023-06-06 15:39 UTC, jainvipin commented on storage/v1alpha1/backend_nvme_tcp.proto
> +    NvmeMultipath multipath = 4;
Minor: we should call this field `NvmeMultipathType` instead of `NVMeMultipath`.

2023-06-06 19:25 UTC, glimchb requested changes
please remove `storage/v1alpha1/google` folder from the commit

2023-06-06 19:44 UTC, glimchb commented on storage/v1alpha1/backend_nvme_tcp.proto
> +    // user can only set {resource}_id on the Create request object
missing:
```
    option (google.api.resource) = {
        type: "storage.opiproject.org/NVMfPath"
        pattern: "volumes/{volume}"
    };
```

2023-06-06 19:45 UTC, glimchb commented on storage/v1alpha1/backend_nvme_tcp.proto
> +    common.v1.ObjectKey id = 1;
id is incorrect, should be:
```
    option (google.api.resource) = {
        type: "storage.opiproject.org/NVMfRemoteNamespace"
        pattern: "volumes/{volume}"
    };
    
    // user can only set {resource}_id on the Create request object
    string name = 1;
```

2023-06-06 19:50 UTC, glimchb requested changes
this patch will fix CI failure:
```
diff --git a/storage/v1alpha1/backend_nvme_tcp.proto b/storage/v1alpha1/backend_nvme_tcp.proto
index 2c51925..413561b 100755
--- a/storage/v1alpha1/backend_nvme_tcp.proto
+++ b/storage/v1alpha1/backend_nvme_tcp.proto
@@ -67,10 +67,10 @@ service NVMfRemoteControllerService {

     rpc CreateNVMfPath (CreateNVMfPathRequest) returns (NVMfPath) {
         option (google.api.http) = {
-            post: "/v1/{parent=subsystems}"
+            post: "/v1/volumes"
             body: "nv_mf_path"
         };
-        option (google.api.method_signature) = "parent,nv_mf_path,nv_mf_path_id";
+        option (google.api.method_signature) = "nv_mf_path,nv_mf_path_id";
     }

     rpc DeleteNVMfPath (DeleteNVMfPathRequest) returns (google.protobuf.Empty) {
@@ -100,6 +100,11 @@ message NVMfRemoteController {
 }

 message NVMfPath {
+    option (google.api.resource) = {
+        type: "storage.opiproject.org/NVMfPath"
+        pattern: "volumes/{volume}"
+    };
+
     // user can only set {resource}_id on the Create request object
     string name = 1;

@@ -128,8 +133,13 @@ message NVMfPath {
 }

 message NVMfRemoteNamespace {
-    // namespace's unique key. Assign to middle/front-end objects.
-    common.v1.ObjectKey id = 1;
+    option (google.api.resource) = {
+        type: "storage.opiproject.org/NVMfRemoteNamespace"
+        pattern: "volumes/{volume}"
+    };
+
+    // user can only set {resource}_id on the Create request object
+    string name = 1;

     // controller through which the namespace is visible
     common.v1.ObjectKey controller_id = 2;
@@ -229,10 +239,6 @@ message ListNVMfRemoteNamespacesResponse {
 }

 message CreateNVMfPathRequest {
-    string parent = 1 [
-        (google.api.field_behavior) = REQUIRED,
-        (google.api.resource_reference).type = "opi_api.storage.v1/NVMfPath"
-    ];
     NVMfPath nv_mf_path = 2 [(google.api.field_behavior) = REQUIRED];
     string nv_mf_path_id = 3;
 }
(END)
```

2023-06-06 22:26 UTC, glimchb commented
> In this case, each NVMfPath is a true NVMe-oF controller (a session) established between a host and a subsystem. These paths are aggregated into an object that behaves like a single NVMe-oF controller - that's what the NVMfController represents (the aggregated thing). An NVMfRemoteNamespace is a namespace - the thing you can read/write - not a controller.

@benlwalker looks like there are no RPCs to create/delete `NVMfRemoteNamespace`... so why have it as an object ? when it is created ? I guess when you connect to remote system with many namespaces, you probably want to create them internally, and then just use them when you reference that object in midllend/frontend... right ?

2023-06-06 22:32 UTC, benlwalker commented
> @benlwalker looks like there are no RPCs to create/delete `NVMfRemoteNamespace`... so why have it as an object ? when it is created ? I guess when you connect to remote system with many namespaces, you probably want to create them internally, and then just use them when you reference that object in midllend/frontend... right ?

If you imagine this is like the Linux kernel, there are no nvme-cli commands to create /dev/nvme0n1 (ignoring format namespace). Instead, you create /dev/nvme0 by connecting to a subsystem and it discovers the namespaces. You then list the namespaces and can mount filesystems on them. This is exactly the same thing. You discover the namespaces, then list them. 

They need to be individual objects because these are what the middle/front end reference when building a middle end bdev or frontend nvmf subsystem. A crypto middle end bdev, for example, would be built on top of one of these namespace objects. Again it's just like Linux (or SPDK) where you create an md raid or a dm-crypt volume on top of /dev/nvme0n1 (the namespace you discovered), not on top of /dev/nvme0 (the controller you created).

2023-06-06 22:37 UTC, glimchb commented
> They need to be individual objects because these are what the middle/front end reference when building a middle end bdev or frontend nvmf subsystem. A crypto middle end bdev, for example, would be built on top of one of these namespace objects. Again it's just like Linux (or SPDK) where you create an md raid or a dm-crypt volume on top of /dev/nvme0n1 (the namespace you discovered), not on top of /dev/nvme0 (the controller you created).

thanks, that is what I figured out as I was writing the question. perhaps similarity with `/dev/nvme0n1` and `/dev/nvme0` somewhere in the comments could help

2023-06-07 16:49 UTC, artek-koltun approved these changes
Looks ok for me. Let's try to implement it in SPDK bridge and see how it fits

2023-06-14 11:38 UTC, artek-koltun reviewed
Worked on [initial implementation](https://github.com/opiproject/opi-spdk-bridge/pull/461) for this API change. I thought about a potential usage scenario: A CSI driver crashed and wants to find out all the paths existed before the crash. It would be nice to have List/Get calls for that purpose as well. However, we have only create and delete...

2023-06-15 13:34 UTC, merged