feat(storage): set annotations for backend
opiproject/opi-api pull request #330
Opened 2023-08-16 07:54 UTC by artek-koltun

See https://github.com/opiproject/opi-api/issues/198 and [AIP-203](https://google.aip.dev/203)

First, let's try to discuss where we are going to keep functionality to connect to local Nvme PCIe drives for JBOF case, since it would affect how to annotate the fields properly. I see an empty separate [backend_nvme_pcie.proto](https://github.com/opiproject/opi-api/blob/main/storage/v1alpha1/backend_nvme_pcie.proto), but also I see `NVME_TRANSPORT_PCIE` enum value in `NvmeTransportType` in [backend_nvme_tcp.proto](https://github.com/opiproject/opi-api/blob/8e3a291121b9f488bd716a693897100665ecd7d9/storage/v1alpha1/backend_nvme_tcp.proto#L372) file, which might imply reuse of the service for PCIe.

Some assumptions/considerations in the first patch:
1. Assumed we can reuse `NvmeRemoteControllerService` for PCIe
2. `FabricsPath` message was created, which is part of `NvmePath`. It allows to annotate some fields as `REQUIRED` for Nvme over fabrics transport types and have more consistent API. Otherwise, we need to keep them `OPTIONAL`, since we can use the same API to connect to local PCIe.
3.  `TcpController` was created to be consistent with previous item and isolate `TCP` related optional parameters. This message is a part of `NvmeRemoteController`.

2023-08-25 15:36 UTC, glimchb requested changes
the annotations looks ok, but creating new message `TcpController` should be discussed and in a separate PR

2023-08-28 08:45 UTC, artek-koltun commented
> the annotations looks ok, but creating new message `TcpController` should be discussed and in a separate PR

ok, I can remove `TcpController` for a while.
However, I want we all to agree on where we want to keep pcie related part: in the existing `NvmeRemoteControllerService` service or in a dedicated one within [backend_nvme_pcie.proto](https://github.com/opiproject/opi-api/blob/main/storage/v1alpha1/backend_nvme_pcie.proto)
@jainvipin  @sburla-marvell @GottliebNoam?

2023-08-29 06:29 UTC, artek-koltun commented on storage/v1alpha1/backend_nvme_tcp.proto
> +    FabricsPath fabrics = 6 [(google.api.field_behavior) = OPTIONAL];
I should warn that we need to mark all fields here as `OPTIONAL` then. Thus, we are loosing some initial validation on these fields by means `fieldbehavior.ValidateRequiredFields`

2023-08-29 06:32 UTC, artek-koltun commented on storage/v1alpha1/backend_nvme_tcp.proto
> +        (google.api.field_behavior) = OUTPUT_ONLY,
I'd oppose. A client cannot create/delete/update `NvmeRemoteNamespace` resources. A client can only list them. Based on that, `REQUIRED` does not make sense here and `OUTPUT_ONLY` is the most suitable choice.

2023-08-29 12:50 UTC, glimchb commented on storage/v1alpha1/backend_nvme_tcp.proto
> +        (google.api.field_behavior) = OUTPUT_ONLY,
I keep forgetting that this `NvmeRemoteNamespace` is a new resource and we don't actually use it yet...
We need to agree how to use it... if this is indeed read-only and we can only list them...
but that seems more like implementation specific thing due to how spdk works...
not sure about this...
I'm ok leaving the annotation like this since we need to have a discussion on this anyways...

2023-08-29 12:52 UTC, merged

2023-08-29 12:53 UTC, glimchb commented on storage/v1alpha1/backend_nvme_tcp.proto
> +    FabricsPath fabrics = 6 [(google.api.field_behavior) = OPTIONAL];
with new PR where you introduce `FabricsPath` you can also change annotation to `REQUIRED`

2023-08-29 13:11 UTC, artek-koltun commented on storage/v1alpha1/backend_nvme_tcp.proto
> +    FabricsPath fabrics = 6 [(google.api.field_behavior) = OPTIONAL];
It depends on what we decide. If we use this service for PCIe as for fabrics, then we cannot require this field. If we use this service for fabrics only, then probably we don't need this message at all

2023-08-29 14:20 UTC, glimchb commented on storage/v1alpha1/backend_nvme_tcp.proto
> +    FabricsPath fabrics = 6 [(google.api.field_behavior) = OPTIONAL];
make sense, let's start the discussion then