feat(storage): modify storage frontend_nvme_pcie proto file to support http api
opiproject/opi-api pull request #333
Opened 2023-08-24 07:14 UTC by chujieyang

Modify the google.api.http definition in the frontend_nvme_pcie proto file in the storage module to better support converting proto to grpc gateway http service

2023-08-24 12:50 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +            patch: "/v1/{nvme_controller.name=nvmeController}"
`/v1/{nvme_controller.name=nvmeSubsystems/*/nvmeControllers/*}` to have a proper variable?

2023-08-24 12:50 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +            get: "/v1/{parent=nvmeControllers}"
maybe `/v1/{parent=nvmeSubsystems/*}/nvmeControllers` since we have a subsys as a parent?

2023-08-24 12:50 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
>              get: "/v1/{name=NvmeControllers/*}"
`/v1/{name=nvmeSubsystems/*/nvmeControllers/*}`?

2023-08-24 12:50 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
>              get: "/v1/{name=NvmeControllers/*}:stats"
`nvmeControllers` with lower case?

2023-08-24 12:50 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +            patch: "/v1/{nvme_namespace.name=nvmeNamespace}"
`/v1/{nvme_namespace.name=nvmeSubsystems/*/nvmeNamespaces/*}`?

2023-08-24 12:50 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +            get: "/v1/{parent=nvmeNamespaces}"
Here we have a namespace as a parent of a namespace. Would it be better to use a subsystem as a parent?
`/v1/{parent=nvmeSubsystems/*}/nvmeNamespaces`?

2023-08-24 12:50 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
>              get: "/v1/{name=NvmeNamespaces/*}:stats"
lower case?

2023-08-25 01:23 UTC, chujieyang commented on storage/gen/grpc-gateway/gen/github.com/opiproject/opi-api/storage/v1alpha1/gen/go/backend_aio.pb.go
> +// SPDX-License-Identifier: Apache-2.0
I will put the auto generated code into a separate commit

2023-08-25 01:29 UTC, chujieyang commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +            get: "/v1/{parent=nvmeSubsystems}"
according to [AIP-132](https://google.aip.dev/132#guidance) , the google.api.method_signature should be "parent"

2023-08-25 06:36 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +            get: "/v1/{parent=nvmeSubsystems}"
Yes, for not a top-level resource. For a top-level resource, AIP-132 says:

> If the resource being listed is a top-level resource, there should be either no google.api.method_signature annotation, or exactly one google.api.method_signature annotation, with a value of ""

2023-08-25 06:52 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +    string parent = 1 [
Why do we need to add `parent` here? To satisfy `pattern` above? The problem here is that we already have a subsystem as parent within `nvme_controller.spec`

2023-08-25 08:26 UTC, chujieyang commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +            get: "/v1/{parent=nvmeSubsystems}"
but the [linter-132](https://linter.aip.dev/132/http-uri-parent) requires: List methods: HTTP URI parent field.  Do we need to violate this rule ?

2023-08-25 08:34 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +            get: "/v1/{parent=nvmeSubsystems}"
I think it complaints due to `parent` field in `message ListNvmeSubsystems`. If we decide that we don't have a top-level resource (parent) for subsystems, we need to adjust all required messages accordingly.
Could you please check if removing of `parent` from List message helps?

2023-08-25 08:43 UTC, chujieyang commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +    string parent = 1 [
NvmeController as an entity that can be associated with its subsystem via spec; it also expects a uri to identify its parent at creation time.

2023-08-28 15:15 UTC, glimchb commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +        pattern: "nvmeSubsystems/{subsystem}/nvmeNamespaces/{namespace}"
excellent, finally somebody fixing this! thank you @chujieyang

2023-08-29 06:16 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +    string parent = 1 [
Yeah, I understand that. We just have a duplication: We have subsystem specified in a parent and within spec which is ambiguous. Should we remove subsystem from spec to avoid this ambiguity? Do we have a kind of reference in protobuf, so we have subsystem in spec autofilled with parent value and vice versa?

2023-08-29 06:56 UTC, chujieyang commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +    string parent = 1 [
Yeah, I think it is a good choice to remove the subsystem in the spec, because the parent has been specified to avoid ambiguity.

2023-09-01 01:44 UTC, chujieyang commented
> @chujieyang please rebase so we can review it again and run through ci I like this work and want to merge this

done

2023-09-01 06:40 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +    string parent = 1 [
We also need to update `NvmeNamespaceSpec` by removing `subsytem_name_ref` as we did here.

Also, this patch will likely require an SPDK bridge rework. Could you prepare a draft to this API change, so we are able to see how the bridge code changed?

2023-09-01 06:40 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +        (google.api.resource_reference).type = "opi_api.storage.v1/NvmeSubsystem"
I am thinking if we aim to support private namespaces. However, it can be a premature consideration

2023-09-01 08:26 UTC, chujieyang commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +    string parent = 1 [
I have `NvmeNamespaceSpec` by removing `subsytem_name_ref`.

As for the draft to this API change, which format doc i need to supply?

2023-09-01 08:28 UTC, chujieyang commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +        (google.api.resource_reference).type = "opi_api.storage.v1/NvmeSubsystem"
I have NvmeNamespaceSpec by removing subsytem_name_ref.

As for the draft to this API change, which format doc i need to supply?

2023-09-01 08:39 UTC, artek-koltun commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +    string parent = 1 [
Thank you, @chujieyang 
I was asking if you could prepare a draft pull request to [opi-spdk-bridge](https://github.com/opiproject/opi-spdk-bridge), so we could see how the code in that repo would change to accommodate this API change

2023-09-01 08:44 UTC, chujieyang commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +    string parent = 1 [
ok, i will submit a pull request after modify the [opi-spdk-bridge](https://github.com/opiproject/opi-spdk-bridge)

2023-09-05 09:01 UTC, chujieyang commented on storage/v1alpha1/frontend_nvme_pcie.proto
> +    string parent = 1 [
I have submit a draft pull request to opi-spdk-bridge and the pr is [610](https://github.com/opiproject/opi-spdk-bridge/pull/610)

2023-09-05 18:15 UTC, glimchb commented on storage/v1alpha1/frontend_nvme_pcie.proto
> -    string nvme_namespace_id = 2 [(google.api.field_behavior) = OPTIONAL];
not sure why `nvme_namespace_id` is deleted here, we need it to change object name...

2023-09-05 18:16 UTC, glimchb requested changes
not sure why `nvme_namespace_id` is removed

2023-09-06 01:08 UTC, chujieyang commented on storage/v1alpha1/frontend_nvme_pcie.proto
> -    string nvme_namespace_id = 2 [(google.api.field_behavior) = OPTIONAL];
I did not delete this. It should be due to the change in the file that the number of lines changed, causing the content of the displayed line to be deleted.

2023-09-06 20:04 UTC, glimchb commented on storage/v1alpha1/frontend_nvme_pcie.proto
> -    string nvme_namespace_id = 2 [(google.api.field_behavior) = OPTIONAL];
ok

2023-09-06 20:05 UTC, glimchb reviewed
@artek-koltun I'm ok with this change, please review as well before we merging it

2023-09-06 20:07 UTC, glimchb approved these changes

2023-09-18 11:50 UTC, artek-koltun approved these changes
Sorry for the delay. LGTM!

2023-09-19 15:19 UTC, glimchb commented
@chujieyang please rebase

2023-09-20 02:38 UTC, merged

2023-09-20 02:47 UTC, glimchb commented
@chujieyang please check the https://github.com/opiproject/godpu/pull/306 that fixes this change API in our client code

you already have draft opened for https://github.com/opiproject/opi-spdk-bridge/pull/610