refactor(common): split inventory from common
opiproject/opi-api pull request #386
Opened 2023-10-10 22:06 UTC by sandersms

Split the inventory from the common folder to allow for adding capabilities along with the inventory.  This also solves the multiple folder issue that was being reported by the inventory file being in the common folder and directed toward an inventory service capability.

2023-10-10 22:12 UTC, glimchb commented
@sandersms please clone [security-skip.yml](https://github.com/opiproject/opi-api/blob/main/.github/workflows/security-skip.yml) and [security.yml](https://github.com/opiproject/opi-api/blob/main/.github/workflows/security.yml) for inventory
we want CI to trigger make

2023-10-10 22:52 UTC, glimchb commented
@sandersms this [line](https://github.com/opiproject/opi-api/blob/53642eec45db20013595897f87474a6b2f728056/inventory/v1/inventory.proto#L19)  needs fix 
```
- option go_package = "github.com/opiproject/opi-api/common/v1/gen/go";
+ option go_package = "github.com/opiproject/opi-api/inventory/v1/gen/go";
```

2023-10-16 06:47 UTC, artek-koltun approved these changes

2023-10-16 06:47 UTC, artek-koltun commented on inventory/Makefile
> +	docker run --user=$$(id -u):$$(id -g) --rm -v "${PWD}":/defs namely/protoc-all:1.51_2  --lint -d v1 -l go -o ./v1/gen/go/  --go-source-relative --with-gateway
you could modify Makefile to use the latest googleapis to build, like in other Makefiles
https://github.com/opiproject/opi-api/pull/387/files#diff-d397fabf5af5abbfeebdcba5c3b68879fb33e5bd432ea70a75e26dbf850a848b

2023-10-16 12:09 UTC, glimchb commented on inventory/Makefile
> +	docker run --user=$$(id -u):$$(id -g) --rm -v "${PWD}":/defs namely/protoc-all:1.51_2  --lint -d v1 -l go -o ./v1/gen/go/  --go-source-relative --with-gateway
+1

2023-10-16 12:09 UTC, glimchb requested changes
tiny makefile fix to match other makefiles...

2023-10-16 15:16 UTC, sandersms commented on inventory/Makefile
> +	docker run --user=$$(id -u):$$(id -g) --rm -v "${PWD}":/defs namely/protoc-all:1.51_2  --lint -d v1 -l go -o ./v1/gen/go/  --go-source-relative --with-gateway
Updated Makefile to use latest googleapis.

2023-10-16 16:19 UTC, glimchb approved these changes
lgtm

2023-10-16 16:21 UTC, merged