Some elaboration on topics already detailed.
opiproject/opi-api pull request #40
Opened 2022-07-19 16:12 UTC by mkalderon

Minor changes and elaboration on some sentences, additional "zoom in" to storage API interface block

Signed-off-by: Michal Kalderon <mkalderon@marvell.com>

2022-07-19 16:14 UTC, mkalderon commented
@glimchb just noticed you pushed some changes, would be great if you can comment on this pull request even though it doesn't merge and if changes seem OK I can handle the merge and resubmit pull request. thanks

2022-07-19 16:15 UTC, mestery requested changes

2022-07-19 16:15 UTC, mestery commented on doc/minutes/images/DPU-storage-plugin.drawio
> +<mxfile host="65bd71144e">
Please save these as editable PNG files rather than Draw.io XML files.

2022-07-19 16:18 UTC, glimchb commented
@mkalderon thank you for posting this, will review now

2022-07-19 16:19 UTC, glimchb commented on storage/spec.md
> +The storage DPU plugin will provide several sets of APIs detailed later on which can be summarized into three main areas:
@mestery insists to use generic `xPU` term instead of DPU

2022-07-19 16:23 UTC, glimchb commented on doc/minutes/images/DPU-storage-plugin.drawio
> +            </root>
+1n for editable PNG

also, I would add user/application facing higher level APIs maybe on the same page ? 

I'm just thinking what we produce? if we produce container/app that runs and receives gRPC and translates them to Vendor SDKs 

and /or we provide LIBRARY... what language bindings ? only c/c++ ? for abstraction on top of Vendor SDKs ?

maybe unrelated to this PR, just sharing my thoughts...

2022-07-19 16:23 UTC, glimchb commented on storage/spec.md
> +In this document we dive into the **OPI Storage API service**
not blocking this PR, but we need to define what is `plugin`... se comment above ? app/container gRPC and/or library ?

2022-07-19 16:25 UTC, glimchb commented on storage/spec.md
> +anything vendors support beyond these would need vendor specific api.
Maybe one of the goals is also to allow vendors to have their own value add not conflicting with OPI, so OPI should allow either plugin or bypass or whatever...

2022-07-19 16:25 UTC, glimchb commented on storage/spec.md
> +(TBD: maybe better illustration ? )
+1 for better illustration

2022-07-19 16:33 UTC, mestery commented on doc/minutes/images/DPU-storage-plugin.drawio
> +            </root>
Does this imply we're producing a shim API layer on top of vendor APIs?

2022-07-19 16:34 UTC, mestery commented on storage/spec.md
> +Initiator server has a DPU which handles NVMeoF connection to Network Storage and exposes some interface to host ( nvme, virtio-blk... ) Host is unaware that storage is not local
Either `xPU` or `DPU / IPU` here.

2022-07-19 16:46 UTC, glimchb commented on doc/minutes/images/DPU-storage-plugin.drawio
> +            </root>
good question. let's discuss...
- one option is to create OPI shim API layer on top of vendor APIs
- in case Vendors want to adopt OPI into SDK, we can remove the SHIM layer

somebody need to listen to gRPC HTTPs TCP port and send to Vendor SDK, no ?

2022-07-19 16:50 UTC, mkalderon commented on doc/minutes/images/DPU-storage-plugin.drawio
> +<mxfile host="65bd71144e">
missed there was such an option will do

2022-07-19 16:51 UTC, mkalderon commented on storage/spec.md
> +The storage DPU plugin will provide several sets of APIs detailed later on which can be summarized into three main areas:
fair enough

2022-07-19 17:00 UTC, mkalderon commented on storage/spec.md
> +In this document we dive into the **OPI Storage API service**
agree

2022-07-19 17:05 UTC, glimchb commented on doc/minutes/images/DPU-storage-plugin.drawio
> +            </root>
on the xPU, for example CSI-like or SMA-like high level request

2022-07-20 11:56 UTC, glimchb approved these changes
thanks @mkalderon few nits to address, but generally approved

2022-07-20 11:56 UTC, glimchb commented on storage/spec.md
> +* compression ()
nit: ()

2022-07-21 13:23 UTC, mkalderon commented on storage/spec.md
> +Standardize middle-end services
maybe I misunderstood the use of Non-Goals in MVP here :-)
The intent of the list was future goals and not necessarily to be part of minimum version...
perhaps not a good place. So just move everything into Goals ?

2022-07-21 17:51 UTC, mestery reviewed
@mkalderon  Can you make sure the `API-GW-Layers.png` file has a white background so it works on dark mode settings?

2022-07-24 09:20 UTC, mkalderon commented
> @mkalderon Can you make sure the `API-GW-Layers.png` file has a white background so it works on dark mode settings?

done

2022-07-24 09:24 UTC, glimchb approved these changes
lgtm
@mestery please approve

2022-07-25 15:04 UTC, mestery approved these changes
We should update `API-GW-Layers.png` to rename the various services as shim APIs instead, but that can be done in a follow-on.

2022-07-25 15:04 UTC, mestery commented on storage/spec.md
> +To define an industry standard “OPI Storage Interface” for IPUs/DPUs that will enable DPU vendors to develop a plugin once and have it work across a number of orchestration systems. The Storage solut
I'm surprised this doesn't hit the markdown linter in terms of line length.

2022-07-25 15:05 UTC, merged

2022-07-25 15:34 UTC, glimchb commented on storage/spec.md
> +To define an industry standard “OPI Storage Interface” for IPUs/DPUs that will enable DPU vendors to develop a plugin once and have it work across a number of orchestration systems. The Storage solut
I disabled LENGTH rule for now, too many places to fix